### ISSUE TITLE
Weird behaviour when passing functions from helpers

### ISSUE THREAD

**Issue by namirsab** [meteor/blaze#47] opened 2016-05-24 08:35 UTC
Hi Everybody!
I'm experiencing a weird thing with Blaze when passing callbacks from helpers that receive a parameter. An example:

``` html
<template name="example" args="parameter">
    {{> childTemplate callback=(callbackGenerator parameter)}} 
</template>
```

``` javsacript
Template.example.helpers({
    callbackGenerator(parameter) {
        return () => {
            console.log(parameter);
        };
    }
});
```

I expected the callbackGenerator to return a function, and this function to be called when `childTemplate` calls it.
But what actually happens is that the function returned is getting immediatly called. It doesn't happen with callbacks without parameters though.
To fix that, we have to write this:

``` javsacript
Template.example.helpers({
    callbackGenerator(parameter) {
        return () => {
            return () => {
                console.log(parameter);
            };
        };
    }
});
```

Is really ugly :disappointed: 

Anything i'm doing wrong?

[post to the forum](https://forums.meteor.com/t/blaze-bugs-when-passing-callbacks/23482)

**Comment by mitar** [comment] 2016-05-24 15:50
I think this is by design. Blaze tries to be helpful and resolve lazy (and often reactive) functions. This is probably something we cannot change in Blaze 1.

A pattern which I am proposing in [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) is to not really have so much complicated logic inside the template. So I would have something like:

```
<template name="example" args="parameter">
    {{> renderChildTemplate}} 
</template>
```

And then a method on the `example` component called `renderChildTemplate` which returns a template with any data context I want.

**Comment by namirsab** [comment] 2016-05-24 23:35
As I pointed in the forum we are going for wrapping functions in objects. That's easy.
What do you think @mitar ?

**Comment by mitar** [comment] 2016-05-27 11:28
Interesting. Then #5 could help you.

**Comment by mitar** [comment] 2016-05-27 11:29
BTW, if you need this for even handlers, you can see in Blaze Components how I attach inline events handlers.

**Comment by namirsab** [comment] 2016-05-27 12:57
@mitar  could you paste a link please?

**Comment by mitar** [comment] 2016-05-27 14:54
You will have to check around the code, it is not in one place: https://github.com/peerlibrary/meteor-blaze-components

**Comment by stubailo** [comment] 2016-08-30 05:01
I feel like a simple fix for this could be to remove automatic calling of functions, and simply ask people to write `helper()` or `helper(arg1, arg2)` in the template. It would be a breaking change, but IMO would make stuff a lot more clearer.

**Comment by mitar** [comment] 2016-08-30 05:04
Oh no, automatic calling functions is so great feature for me. I really like that it resolves. I am used to that from Django as well.

**Comment by namirsab** [comment] 2016-08-30 07:58
I agree with @stubailo 
I don't really dislike the automatic function calling, but I think sometimes is weird, like in the case that opens the issue.
This is for me not even helpful because it's not intuitive. Do you think this is a great feature?
Could you explain me what is what makes it so great?
I'm maybe missing something.
Thanks!

**Comment by mitar** [comment] 2016-08-30 08:01
That you do not have to think if something is a property or a function/helper. You do not have to change the template once you move from a property to a function/helper.

**Comment by namirsab** [comment] 2016-08-31 07:47
that's true in a simple case like this:
```html
<template name="simple" args="prop1 prop2">
     {{>anotherTemplate prop=prop1}}
</template>
```
In this case, if we change prop1 to a helper, it wil behave the same.

But in cases where you are explcitly "calling" a function with the following syntax:
```html
<template name="simple" args="prop1 prop2">
     {{>anotherTemplate prop=(fn prop1)}}
</template>
```
In this case you cannot replace this like before, and the behaviour is weird, because you know you are calling the first function (`fn`) but you don't expect (at least for me is not really intuitive) that the function returned by `fn` is going to called to.
I don't see here any advantage, just a weird behaviour. Maybe there is something im missing again...
Thanks!

**Comment by filipenevola** [comment] 2021-03-18 19:28
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:28 UTC
