### ISSUE TITLE
get rid of jquery for vdom

### ISSUE THREAD

**Issue by devagrawal09** [meteor/blaze#271] opened 2017-09-21 15:52 UTC
Get rid of all DOM updates done using jQuery and use something like google's [incremental dom](https://github.com/google/incremental-dom). 3 advantages - faster, smaller, support server side rendering.

**Comment by mitar** [comment] 2017-09-21 16:13
Duplicate of #45. We looked into this and at the end it didn't look like incremental DOM is an easy thing to transition. But maybe you can do a pass on it and try to show how it could be done. In any case, discuss it in that issue.

**Closed by mitar** 2017-09-21 16:13 UTC
