### ISSUE TITLE
The insertElement UI hook doesn't fire when the template gets first rendered

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#188] opened 2016-11-29 14:08 UTC
Migrating this over from meteor/meteor#2347. Yes this is still the case, but the [current state of `_uihooks` wasn't intended to be the final API](https://groups.google.com/forum/#!msg/meteor-core/1kUoG2mcaRw/j4bNvXu36IoJ). Maybe UI hook support should be made an official part of Blaze (with the `_` naming removed) and documented? Might be off-topic for this issue, but something to consider ...

----

(originally reported by @frozeman)

On following template renders, it gets fired.
Should i create a repro, or are you aware of this already?

**Comment by mitar** [comment] 2016-11-29 14:11
I had to fix this quite a bit to make it work for Blaze Components. (There, you get hooks for every insertion/removal, not just at the top-level.)

But I would need reproduction for this, @frozeman. Because I a do not think I noticed an issue with first insert.

**Comment by hwillson** [comment] 2016-11-29 14:25
My guess is that @mizzao nailed it with https://github.com/meteor/meteor/issues/2347#issuecomment-50542443. So if attaching the hook  like:

```
Template.someTemplate.onRendered(function onRendered() {
  this.firstNode.parentNode._uihooks = {
    insertElement(node, next) {
      // Do something ...
    },
  };
});
```

there could be a timing issue if data has already arrived before the hook was registered.

**Comment by mitar** [comment] 2016-11-29 14:27
Oh, yes. This is why I am in Blaze Components looking for a method on the template/component, and not on a DOM node. What a strange API.

**Comment by filipenevola** [comment] 2021-03-18 19:37
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:37 UTC
