### ISSUE TITLE
Single File / Single Object Blaze Templates

### ISSUE THREAD

**Issue by msavin** [meteor/blaze#126] opened 2016-09-29 14:34 UTC
React hasn't inspired a positive attitude in many of us in regards to combining HTML with JavaScript. However, sometimes when writing small pieces, I do think, it would be nice if I can just chunk it one block. I haven't seen this kind of approach discussed, but I think it would deliver that and be easy to built and transition into:

``` javascript
Template.register({
    bigButton: {
        view: function () {
            return `
                <button class="{{state}}">
                    {{label}}
                </button>               
            `;          
        },
        events: {
            'click': function () {
                // ...  
            },
            'render': function () {
                //...           
            }
        },
        helpers: {
            label: function () {
                // ...      
        }
    }
});
```

The developer could choose whether to use the `view` field or define their html in a <template> tag. 

I suppose we can even throw `style` into the mix. Maybe CSS support would like: if browser supports CSS variables, use them, otherwise, use the "default" variable value. 

---

In pursuit of template groups (#100), we can even do it something like:

``` javascript
Notifications = new Blaze("notifications");

Notifications.register({
    notifications: {
        // ...
    },
    notification: {
        // ...
    }
});
```

I'm big on grouping because we can import and export pieces of an application instead of focusing on a template at a time. I believe that's the right level of abstraction.

... Later, we can do a beauty contest comparing Blaze code to React's :P

**Comment by aadamsx** [comment] 2016-09-29 15:46
ouuuu hhhha -- really like that code snippit!  Looks good and seems like something that would feel great to use!

**Comment by mitar** [comment] 2016-09-29 16:52
Isn't this duplicate of: #94

**Comment by mitar** [comment] 2016-09-29 16:53
Personally, I am against this style that HTML is embedded inside JavaScript. If you want that style, go with React.

But I am OK with style of having JavaScript embedded inside HTML.

**Comment by aadamsx** [comment] 2016-09-29 16:58
> If you want that style, go with React.

Haha.  I'm with you for the most part, JS inside of HTML.  

But If he can build this feature with a PR, why not have the option?

**Comment by mitar** [comment] 2016-09-29 18:26
> But If he can build this feature with a PR, why not have the option? 

Because every feature somebody has to maintain as well.

**Comment by necmettin** [comment] 2016-09-30 08:48
I'm against this. I do not want to see HTML inside Javascript. That is the single most important reason I'm not using React everyday.

Also, the example uses `, which is used in ES6 for template strings. That's a no-no.

Also, ideas are good, but I'm against implementing features for the sake of features. Implementing features is the easier part of having them. Time spent to maintain a feature is (for the most part) more than the time spent implementing it. We should not cram everything we can think of into Blaze.

**Comment by mitar** [comment] 2016-09-30 08:51
(Just a note: please upvote/downvote the issue itself, besides making comments.)

**Comment by laosb** [comment] 2016-09-30 09:03
Personally I'm again having HTML in JavaScript, but with the ES6 syntax, I guess we should have this option for developers. For small components it's even easier to understand the whole component.

**Comment by msavin** [comment] 2016-10-05 14:39
My thinking here was; Blaze already just takes the string from in between the <template> tags, so supporting an option to pass a string directly into it should be easy. In that case, if I understand correctly, we'd be writing a bit of sugar over what Blaze already has.

Other points worth discussing:

1. Should Blaze allow developers to mix languages?
My opinion: HTML in JS, and/or JS in HTML, and even CSS in HTML, or HTML in CSS, can all be undesirable. For JS-in-HTML, we have something great for that: Spacebars/Handlebars.

2. Should we support ES6 template strings?
My opinion: ES6 templates strings change the case here for HTML in JS, and with a good text editor configuration, maybe the template block can be highlighted in a way to distringuish it from the rest of the JavaScript, and even color it as HTML. 	

3. Should Blaze adopt single file views if only for marketing? 
My opinion: The  approach is popular, as evident with Vue and React, and supporting it it could greatly improve the marketability of Blaze.  In that case, Blaze starts to look a bit like React, but with support for regular HTML, which many people wish React had.

**Comment by aadamsx** [comment] 2016-10-05 15:20
@msavin, If we are talking about about Blaze 2.0, then I think we should be talking about https://github.com/meteor/blaze/issues/128#issuecomment-251227758 instead of duplicating efforts or talking ourselves in circles with this minor stuff.  

Vue has the momentum in the broader JS community.  Vue has the features we've been asking for and need.  Vue has the performance.  Vue has developers working full time on the project.  The only thing it's lacking is tight Meteor integration.

I think we should be discussing how to build off Vue with a emphasis on Meteor -- as a Blaze 2.0 and not get sidetracked by talk of single file, etc. 

We need to be looking at the big picture here.

**Comment by janat08** [comment] 2017-07-01 22:36
vue is tightly bound to html, and react is spam of new files/components.

**Comment by tvogt** [comment] 2018-07-10 06:31
Note that this is an entirely different discussion than JSX. That abomination mixes JS and HTML, 15 years after we finally managed to seperate them. But the concept of having HTML, JS and CSS in the same **file**, but in different **sections** just makes life so much easier.

`
<template>
(your HTML here)
</template>

<script>
(your JS here)
</script>

<style>
(your CSS here)
</style>
`

that is just so much of an approach when you think in components that I was surprised it isn't the Meteor/Blaze default.

**Comment by filipenevola** [comment] 2021-03-18 19:34
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:34 UTC
Labels: discussion
