### ISSUE TITLE
Enable locally-scoped, importable Blaze templates

### ISSUE THREAD

**Issue by akanix42** [meteor/blaze#15] opened 2016-03-25 16:08 UTC
Today, Blaze templates are global. I propose we add an alternate, locally-scoped/ES 2015 import compatible syntax. I've already implemented a version of this by modifying the [blaze-html-templates package (and related subpackages)](https://github.com/nathantreid/blaze-modules) to enable a `<component>` tag that is default export from the generated JS file. 
The [code changes](https://github.com/nathantreid/blaze-modules/commit/b66e3821f6efc48dbc5da9f3d70631b3fc2bb98a) are pretty small and don't affect the existing global templates.

I have an [example app on Github](https://github.com/nathantreid/blaze-modules-example) that includes mixing normal templates with the local templates, but following is a quick sample of the new syntax. The local templates use the `<component>` tag because I needed a different one than `<template>` and it's the first one I came up with.

component1.html

``` handlebars
<component name="component1">
Testing {{> component2}}
</component>
```

component2.html

``` handlebars
<component name="component2">
1 2 3.
</component>
```

component1.js

``` js
import component1 from './component1.html';
import component2 from './component2.html';

component1.helpers{{ component2 });
```

**Comment by zol** [comment] 2016-03-29 00:34
+1

**Comment by mitar** [comment] 2016-04-17 03:49
This is amazing. I would love to see this be moved to core Blaze, but I assigned this to the "Future ideas" milestone because I think we should first do some basic improvements to Blaze ecosystem to be able to easier get such improvements into Blaze.

**Comment by mpowaga** [comment] 2016-05-16 14:48
Nice job @nathantreid! I would love the final implementation to have following features:

* import inside blaze files

```html
<import template="component1" from="./component1.html">
<import template="component1" as="component2" from="./component1.html">
```

* keep template tag and add export attribute

```html
<template name="component" export>
  ...
</template>
```

* export multiple templates

```html
<!-- exported as default template -->
<template name="component1" export="default">
  ...
</template>

<!-- exported as component2 -->
<template name="component2" export>
  ...
</template>

<!-- exported as component -->
<template name="component3" export="component">
  ...
</template>
```

**Comment by mitar** [comment] 2016-09-09 16:10
I would suggest that we make it simpler and simply keep `template`. So I would suggest (as proposed in #75) that we simply make that every `.html` package becomes a JavaScript module, and every template exports its template as a symbol with template name from that module. If you do not want to export, we can add (lower priority to me) something like `<template name="Foo" private="true">`. But  default would be exporting (I do not see really arguments against that to be the default, but it would make boilerplate simpler).

Moreover, every exported template at that spot in the template module simply assigns it to `module.exports` object. So if you want to fine tune it, you can add a `<script>` tag at the end of your template module and modify `module.exports` further.

**Comment by mitar** [comment] 2016-09-09 16:21
I think the only question is, do we still register templates into a global namespace? Because the issue is that they have to be unique there.

**Comment by nathantreid** [comment] 2016-09-09 19:25
That's the reason why I went with a `<component>` tag - I also wanted to have exports / local by default, but also needed to keep compatibility with existing apps / "Meteor Classic". I definitely think we should be avoiding the global namespace, but I'm wary of making a change that will break all existing Blaze templates.

> Moreover, every exported template at that spot in the template module simply assigns it to `module.exports` object. So if you want to fine tune it, you can add a `<script>` tag at the end of your template module and modify `module.exports` further.

This is great!

**Comment by mitar** [comment] 2016-09-09 21:45
Yea, but I would prefer to make it compatible instead of introducing a new tag. I think it could be done with some help of Meteor migration. So we could make Blaze not export any templates by default.

And then we would have `blaze-global-templates` which would on the app scope export all templates defined there, and on package scope as a dependency export all templates of the package. And then Meteor migration would add it to app packages.

Moreover, using `<script>` you could simply register template globally as well in the new system. If you need one template to be global for some compatibility.

Alternatively, we could just bump major version and make it not compatible change and this is it. I also think we should not be too scared of doing incremental changes with clear upgrade paths and documentation.

**Comment by mitar** [comment] 2016-09-09 21:49
One other thing could be also adding an option to `addFiles` which would make things global or not for all Blaze `.html` files inside that call.

Like:

```javascript
api.addFiles([
  'foo.html'
], {exportGlobally: false});
```

I think this might even be the best option. And then we can have a deprecation warning for some time that default will be switched to `false` in few versions. I really like how Django is upgrading their code. Where for every backwards incompatible change they make a plan, and first introduce a warning, and then make a change. So if you would not have `exportGlobally` option at all (true or false) you would get a warning. And then we change default and remove a warning after few versions.

**Comment by mitar** [comment] 2016-09-09 21:52
I think we do not need `<import>` tags if we have `<script>` tags.

One other change I would do is make `{{> symbol}}` resolve to a variable `symbol` and not string `"symbol"`. So then the question is just how you get that symbol into a template, which could be using script, using a helper, or whatever. And there could be a global helper for importing a template. Like

```
{{> (require './foo.html' 'Bar')}}
```

**Comment by nathantreid** [comment] 2016-09-09 22:13
> One other change I would do is make {{> symbol}} resolve to a variable symbol and not string "symbol".

This already works in Blaze today; if you pass in the template `symbol` via a helper, it will display the template.

**Comment by mitar** [comment] 2016-09-09 22:16
> This already works in Blaze today; if you pass in the template symbol via a helper, it will display the template.

Yea, but if it is not a helper, then it is used as a string and tries to be resolved as a global template. Maybe that is a good transition mechanism, but maybe we should be stricter here. So if you want a global template, you should use `{{> 'symbol'}}`.

**Comment by nathantreid** [comment] 2016-09-09 22:18
The `blaze-global-templates` package sounds good to me - breaking change, but providing a simple backwards compatible extra plugin.

> ```js
> api.addFiles([
>   'foo.html'
> ], {exportGlobally: false});
> ```

I really dislike this because it only works inside of packages, and even then only works if you aren't just using `api.mainModule`.

**Comment by laosb** [comment] 2016-09-09 22:23
@nathantreid I agree with you.

**Comment by laosb** [comment] 2016-09-09 22:27
@mitar This breaks backwards compatibility, almost breaks all existing apps. I would prefer an `<import>`, like `<import src='../xxx.html' as='whatever'>`.

**Comment by mitar** [comment] 2016-09-09 22:29
> I really dislike this because it only works inside of packages,

We could use the above mentioned package 

> and even then only works if you aren't just using api.mainModule.

But isn't this perfect? If you are not doing `addFiles`, but just importing it, then you are not exporting it globally. It exports a template globally only if you do `addFiles`, and then you can configure it to not do so. No?

**Comment by mitar** [comment] 2016-09-09 22:30
> This breaks backwards compatibility, almost breaks all existing apps.

What exactly breaks all compatibility?

**Comment by laosb** [comment] 2016-09-11 21:46
>but maybe we should be stricter here. So if you want a global template, you should use `{{> 'symbol'}}`.

Maybe I misunderstood something?

**Comment by vblagomir** [comment] 2017-03-19 21:41
Just tried blaze-modules, looks just amazing! Very elegant and understandable solution. Considering Meteor 1.5 is about lazy loading, thumbs up to include this in any of upcoming versions of Blaze.

**Comment by filipenevola** [comment] 2021-03-18 19:31
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:31 UTC
