### ISSUE TITLE
will this ever be on npm

### ISSUE THREAD

**Issue by MaxPleaner** [meteor/blaze#269] opened 2017-08-12 19:19 UTC
It says in the readme that it's only meteor for now, but will have npm support added. Just curious if that is still in the works? I wanted to try out blaze with some custom webpack build routine for a client-only site

**Comment by janat08** [comment] 2017-08-12 20:29
https://github.com/meteor/blaze/issues/11

**Comment by mitar** [comment] 2017-08-12 21:33
Duplicate of #11 and #13.

**Closed by mitar** 2017-08-12 21:33 UTC
