### ISSUE TITLE
Data context in a for each loop not properly set

### ISSUE THREAD

**Issue by braadworst** [meteor/blaze#48] opened 2016-06-23 21:32 UTC
I am using Meteor 1.3.4 and I am struggling with the data context in a for each loop. In the previous version of Meteor 1.2.x I could have a {{# each }} loop in my template and add and event on the iterated elements. When I would need the data object that was looped I could just use the _this_ keyword in the Template.x.events method and I would get the data context.

I seems in meteor that you now explicitly have to create a new include {{> templatename }} to get the data context. Can someone confirm this? And is there another option with adding a new template for each element in a loop. Some stuff is to simple to loop over and putting it in a new template, just for the context.

Cheers Roy

**Comment by mitar** [comment] 2016-06-23 21:34
Can you please show a working small reproduction. Something which worked before and it does not work now?

**Comment by filipenevola** [comment] 2021-03-18 19:28
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:28 UTC
