### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#209] opened 2016-12-12 20:04 UTC
Migrating over from meteor/meteor#2980.

----

(originally reported by @mitar)

I am getting the following error at [this location](https://github.com/meteor/meteor/blob/devel/packages/blaze/domrange.js#L223):

```
Exception from Tracker recompute function: Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at DOMRange.detach (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:508:24)
    at DOMRange.setMembers (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:467:12)
    at doMaterialize (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:1866:22)
    at Object.Tracker.nonreactive (http://127.0.0.1:3000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:502:12)
    at doRender (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:1856:15)
    at http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:1795:16
    at Object.Blaze._withCurrentView (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:2029:12)
    at viewAutorun (http://127.0.0.1:3000/packages/blaze.js?7b6d333ab34b433f99b0a25d999d47d9b2c39f32:1794:18)
    at Tracker.Computation._compute (http://127.0.0.1:3000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:288:36) debug.js:41
```

Sadly I could not make a small reproduction.

**Comment by PAGG-ESkopal** [comment] 2017-02-15 13:36
I am having still this problem as well.  Why was this issue closed?

**Comment by hwillson** [comment] 2017-02-15 13:40
Hi @PAGG-ESkopal - this issue wasn't closed; it's open here. The original issue was closed since it has since been migrated over to this repo.

**Comment by PAGG-ESkopal** [comment] 2017-02-15 13:41
Thanks for the update.  I saw the "closed" tag and thought it was referring to this issue.  Thanks for letting me know.

**Comment by PAGG-ESkopal** [comment] 2017-02-15 13:51
So, I have tracked down quite a bit of what is happening here.  I have an application that is displaying an array of objects as rows (using {{each}}).  When I delete one of those rows, that has a text field that is empty, above a row that has data in that same field, during Blaze re-rendering (due to a reactive source), this error is occurring. 

If I delete rows below the row containing data in the field, no problem.  When I delete rows where the field is empty above other rows where the field is also empty, no problem.

I am using X-Editable.  X-Editable happens to put data in the empty text area in the DOM after it was rendered by Blaze.  I am working through that code now.

**Comment by mitar** [comment] 2017-02-15 17:11
> When I delete one of those rows

How do you delete rows? Directly in DOM? Then it is not strange that Blaze complains.

**Comment by PAGG-ESkopal** [comment] 2017-02-15 20:55
I put the array of objects into a reactiveDict in the .onCreated function.  When I delete a row, I deep copy each of the remaining rows objects into a new array, then assign it to the reactiveDict.  That causes Blaze to re-render.  In the .onRendered function I call the X-editable routines that prepare the item for editing.

I did have to add a autorun inside of .onRendered to get the X-editable code to re-run when the data changes.  I create a table of reactiveDicts for each enclosing item.  This allows me to find the appropriate reactiveDict based on the _id.

`this.autorun(function () {
        const dict = myapp.reactiveDicts[this.data._id];
        const tasks = dict.get('tasks');
        Tracker.afterFlush(function () {
            if (typeof dict !== 'undefined') {
                myapp.showPartTasks.tasksXeditableSetup(tasks);
            }
        }.bind(this));
    }.bind(this));`

This actually took quite awhile to find someone explaining how to get .onRendered to run over and over again.

**Comment by mitar** [comment] 2017-02-15 20:57
So, can you confirm: are you editing DOM yourself and then Blaze complains?

**Comment by PAGG-ESkopal** [comment] 2017-02-15 21:00
Yes.  X-Editable manipulates the DOM to allow editing.  I am looking through that code now.

**Comment by PAGG-ESkopal** [comment] 2017-02-15 21:02
I think Blaze is trying to be very clever to minimize the redrawing, instead of just re-rendering and that is where the problem arises.

**Comment by mitar** [comment] 2017-02-15 21:05
Then this is a problem in your code and not Blaze.

I see also that the original bug was connected to content editable.

When you have content editable, you should not render content using Blaze. So this is a no go:

```handlebars
<editor>{{content}}</editor>
```


What you want to do instead is:

````handlebars
<editor></editor>
````

```js
...onRendered(() => {
  this.autorun((() => {
    this.$('editor').myEditorAPI.setContentTo(reactiveContentVariable.get());
  });
});
```

So your content editable plugin often has some API to set its contents, you should use that.

**Closed** 2017-02-15 21:05 UTC
Labels: bug, contributions welcome

**Comment by PAGG-ESkopal** [comment] 2017-02-15 21:45
Well, I don't think that is a very good response.  I think this issue should remain Open and I would like assistance if I don't understand some part of Blaze.

I didn't create the initial problem report, I have just run into the same issue.  I rather like the Blaze tool and I plan to keep using it.

I have over a year's worth of code written to use Blaze and Autoform (and iron-router).  However, new features are making the data too complex for my users to continue to edit it with Autoform.  I am trying to move toward a more user friendly solution.  X-Editable handles individual fields -- not entire pages.  I would like to continue to use Blaze for drawing the overall form -- since that is what I am familiar with.  Blaze is wicked clever about drawing the html pages.

This is the ONLY area where I have run into trouble with Blaze.  Adding, Deleting and Editing are working flawlessly, when there are updates or when you add a new row.  There is just one special case of deleting where it is failing.

As a number of people have run into this issue, I think it would be better to find a way to get it to work - making Blaze a better and more flexible tool for everyone.

I am working on the problem and plan to share my findings with the community.   I just wanted to make sure I wasn't overlooking anything (as I thought the issue was closed).  I am also hoping to get any pointers that might help me resolve the issue.

That is the whole idea of "community" -- we help each other out.

**Comment by mitar** [comment] 2017-02-15 21:55
Not sure what are you trying to say. I opened initial issue with this (in 2014). I spent few years trying to came up with a solution, and I have found out that Blaze is not at fault here, but it is how one integrates content editable with Blaze. And I shared how one should integrate it, if you want to do it properly.

You can find and propose other ways to integrate it, but from the point of Blaze, this is not a bug. One should not be changing DOM underneath it. Many other libraries like React and others have similar issues. Blaze is pretty good to try to do a good job here, even if you do change DOM, but it cannot be perfect. And I do not think we can make it perfect. So, you have to approach this issue differently. You have an example on how to do that above.

The issue is just closed, not locked for future discussion by the community.

**Comment by PAGG-ESkopal** [comment] 2017-02-16 17:47
Well, I have solved the problem.  Actually, your suggestion helped, but, not in the way you might expect.

Instead of stopping Blaze from rendering the data, I stopped the editing package from doing so.  I rely on the reactive variable to re-render the updated data using Blaze.  I had to add more Blaze code to apply the appropriate classes as the data was edited.

X-editable doesn't have any good way to create and display the data, but it does have "display=false", which instructs it not to update the display itself.

**Comment by mitar** [comment] 2017-02-16 20:00
That is another approach. This is also current best practice for using jQuery UI sortable. You use it to show effects, but then you do not allow it to edit DOM at the end, but update the data, and leave to Blaze to update the DOM.

I am glad that it works in this case as well.
