### ISSUE TITLE
Add to blaze package readme that repository is here

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#57] opened 2016-08-29 03:13 UTC
In readme and [here](https://atmospherejs.com/meteor/blaze) we should point to this repository to help users with transition. [Some background](https://github.com/meteor/blaze/issues/20#issuecomment-243023019).

**Comment by alexandesigner** [comment] 2016-09-01 14:21
@mitar I think we can close this issue

**Comment by mitar** [comment] 2016-09-01 19:22
No? We have to update [this README](https://github.com/meteor/blaze/blob/master/packages/blaze/README.md).

So we have now three copies of this content:
* https://github.com/meteor/blaze/blob/master/packages/blaze/README.md
* https://github.com/meteor/blaze/blob/master/site/source/index.md
* https://github.com/meteor/blaze/blob/master/README.md

I think the first one should be simple content pointing  to http://blazejs.org for more information and docs.

And the last one should be more developer (of Blaze itself) oriented but also simple content pointing to http://blazejs.org for end-developer documentation and docs.

Currently, https://github.com/meteor/blaze/blob/master/README.md seems to be the most recent content which should then be moved to https://github.com/meteor/blaze/blob/master/site/source/index.md instead.

Could you make a pull request organizing this?

**Comment by alexandesigner** [comment] 2016-09-01 20:28
Heey, I suggested we close in favor of this issue: https://github.com/meteor/blaze/issues/66 _(We would continue this discussion there.)_ Since this is the issue to "add to blaze..." and so was done!

> I think the first one should be simple content pointing to http://blazejs.org for more information and docs.

I agree, I think the content here should be very short and objective, I will think the best way to present it.

> And the last one should be more developer (of Blaze itself) oriented but also simple content pointing to http://blazejs.org for end-developer documentation and docs.

Similarly I think the readme (https://github.com/meteor/blaze/blob/master/README.md) of the repository should be simple and objective.
 
>Currently, https://github.com/meteor/blaze/blob/master/README.md seems to be the most recent content which should then be moved to https://github.com/meteor/blaze/blob/master/site/source/index.md instead.

I'm going to organize.

**Comment by mitar** [comment] 2016-09-01 20:29
See [the background discussion here](https://github.com/meteor/blaze/issues/20#issuecomment-243023019) to understand what is this issue about. :-) Why I opened it (to not forget about that particular point).

**Comment by alexandesigner** [comment] 2016-09-01 20:34
No problem, i'm sorry! 😄

**Comment by mitar** [comment] 2016-09-01 20:36
But yes, please include this in your pull request when organizing the READMEs and then we can close it. :-)

**Comment by mitar** [comment] 2016-09-01 20:36
(And no problem, I am sorry if I made this issue unclear. It was really just a note to not forget.)

**Comment by mitar** [comment] 2016-09-05 22:58
@tmeasday: Do you think the [README which will go to Atmosphere](https://github.com/meteor/blaze/blob/master/packages/blaze/README.md) is good enough [based on your comment](https://github.com/meteor/blaze/issues/20#issuecomment-243023019)?

**Comment by tmeasday** [comment] 2016-09-05 23:28
@mitar looks great. Let's see how it goes as you do releases. We might hit a few roadbumps in terms of what exact command people need to use to take a new version of Blaze but I'm sure we can get over them.

🎉

**Comment by mitar** [comment] 2016-09-05 23:35
Perfect.

I do not think when a release will be ready. We are just working on infrastructure at the moment. But maybe we should just make one dummy release to get versions to some rounded numbers to make it easier to have documentation for versions.

BTW, do you know what is the status of that Blaze bug about "is object" on Chrome? I remember seeing that but I do not find it now.

**Comment by tmeasday** [comment] 2016-09-05 23:44
It's this one: https://github.com/meteor/meteor/issues/6793 -- looks like it's not yet fixed in the latest chrome (53)

**Comment by mitar** [comment] 2016-09-05 23:46
Could you look into creating a test and fix for it into this repository an then maybe this could be the first release?

**Comment by tmeasday** [comment] 2016-09-06 00:21
Hmm, well I was not "fixing" it because
a) it really seems to be a chrome bug, I'm not sure why it hasn't been fixed
b) I have no idea of the implications of changing the definition of a fundamental utility like that. It seems like it hasn't caused problems for people, but I'd prefer not to do it if we can help it.

**Comment by mitar** [comment] 2016-09-06 00:22
Did anyone reported this upstream?

**Comment by tmeasday** [comment] 2016-09-06 00:32
I think @nathan-muir is the one to ask about this.

**Comment by nathan-muir** [comment] 2016-09-06 02:12
I didn't report this upstream, as last time I tested, I wasn't able to reproduce it above v5.1.

I'm flat out at the moment - so if you wanted to verify - try following the steps from my comment here: https://github.com/meteor/meteor/issues/6793#issuecomment-228249243

**Closed** 2016-09-13 09:02 UTC
