### ISSUE TITLE
Blaze not setting "selected" attribute

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#210] opened 2016-12-12 20:27 UTC
Migrating over from meteor/meteor#3191.

----

(originally reported by @lourd)

See [this repo](https://github.com/lourd/meteor-select-attr-issue) and [this demo](http://select-attr-issue.meteor.com/).

Basically passing in an empty string to a `selected` attribute isn't working correctly. When setting multiple attributes as an object, e.g.

```
// Template
<select>
  <option {{ optionAttrs 'default' }}>Select an option</option>
  <option {{ optionAttrs 'one' }}>Option one</option>
  <option {{ optionAttrs 'two' }}>Option two</option>
  <option {{ optionAttrs 'three' }}>Option three</option>
  <option {{ optionAttrs 'four' }}>Option four</option>
</select>

// Helper
optionAttrs : function ( option ) {
  var attrs = {};
  if ( option === 'default' ) {
    attrs.value = "";
    attrs.disabled = "";
  } else {
    attrs.value = option;
  }
  // If it's option three, make it selected
  attrs.selected = option === 'three' ? "" : false;
  // passing in true instead of empty string didn't change the behavior
  // attrs.selected = option === 'three';
  // Neither did returning 'selected'
  // attrs.selected = option === 'three' ? "selected" : false;
  return attrs;
}
```

The selected attribute doesn't turn up at all.

When setting the selected attribute explicitly, the correct `option` is selected (verified by getting the value on the `select` element), but the option that's supposed to be selected still doesn't actually have a `selected` attribute.

```
// Template
<select>
  <option selected={{ isSelected 'default' }}>Select an option</option>
  <option selected={{ isSelected 'one' }}>Option one</option>
  <option selected={{ isSelected 'two' }}>Option two</option>
  <option selected={{ isSelected 'three' }}>Option three</option>
  <option selected={{ isSelected 'four' }}>Option four</option>
</select>

// Template helper
isSelected : function ( option ) {
  return option === 'three' ? "" : false;
}
```

This does not follow the behavior as documented in the [Spacebars README](https://atmospherejs.com/meteor/spacebars), the [Meteor manual](http://manual.meteor.com/#blaze-reactiveatts), or the [wiki article on using Blaze](https://github.com/meteor/meteor/wiki/Using-Blaze#conditional-attributes-with-no-value-eg-checked-selected).

I've tested this on OS X 10.10 and 10.9 using Safari, Firefox, and Chrome, and iOS 7 and 8.

**Comment by mitar** [comment] 2016-12-31 09:23
This has been recently fixed when fixing #52. The issue is that `false` value for dynamic attributes was treated as true. In reproduction above, if the line:

```
attrs.selected = option === 'three' ? "" : false;
```

Is changed to:

```
attrs.selected = option === 'three' ? "" : null;
```

It works correctly in older versions. This has been fixed now and also `false` works.

The second thing, that `selected` attribute is not set is by design and with explicit exception for this in the code. Blaze sets only property for `selected` and `checked`. You can see that on the DOM element. Property is not set, but attribute is. The attribute in fact corresponds to the `defaultChecked` property. See more discussion about this in [jQuery documentation](https://api.jquery.com/prop/).

**Closed by mitar** 2016-12-31 09:23 UTC
Labels: bug
