### ISSUE TITLE
project not working after update to blaze 2.2.1  (ok with 2.2.0)

### ISSUE THREAD

**Issue by deeeed** [meteor/blaze#230] opened 2017-01-10 04:27 UTC
Just tried to update to latest 2.2.1, but I can an error from a custom package using SimpleSchema.

It seems the error comes from adding "custom" property to my schema with:
```
autoform: {
            type: "select-buttons",
            options: "allowed",
            aCustomProp: false,
        }
```
![image](https://cloud.githubusercontent.com/assets/4800095/21793798/85e6216a-d72f-11e6-9423-b8ad1c15c64b.png)

Unfortunately, I don't have time to investigate more. I forced @2.2.0 for now.

**Comment by mitar** [comment] 2017-01-10 04:31
Duplicate of #228. It has been fixed in master.

**Closed by mitar** 2017-01-10 04:31 UTC
Labels: bug, duplicate

**Comment by jykae** [comment] 2017-01-11 13:47
@mitar this is fix possibly coming to next release? we probably stay in previous release then.

**Comment by mitar** [comment] 2017-01-12 03:26
Released as 2.3.0.
