### ISSUE TITLE
Investigate adding the kernel to blaze / tracker

### ISSUE THREAD

**Issue by raix** [meteor/blaze#149] opened 2016-11-06 07:23 UTC
@mitar:
> Oh, I am sad to read that using kernel has bad side-effects. Because that is one of things I was planing to integrate into Blaze/Tracker at some point. It seems like a reasonable thing to do. But probably it really can have some side-effects. It would be great to learn which exactly side-effects are.

I'll try to write up some of the potential side effects in this issue,

In short I have to say that the kernel saved performance for one of our apps, basically because reactive updates can get out of hand and block the UI - the kernel makes sure that autoruns only run when theres time for it, leaving time for the browser to render the ui without dropping frames.

The kernel keeps the context but breaks the contract of sync, everything is defered. Normally that should actually not be an issue because you don't have control of when autoruns are invalidated.
But you might experience issues if you are manhandling the template instance from an onRender autorun that runs after the template is destroyed.

There also seem to be an issue with nested blaze autoruns (I think it's just a context issue that needs to be taken into account)

@mitar I think it's solvable, let me know if you want me to improve blaze performance using parts of the kernel.

**Comment by mitar** [comment] 2016-11-06 07:27
One reason why I was thinking of using request animation frame was because manipulating DOM should be cheaper inside that callback.

**Comment by raix** [comment] 2016-11-06 09:44
I'm not sure if its cheaper - but raf is called just before layout calc etc. so it might provide with some additional control for optimization.
From my point of view having reactivity no block rendering / UI is a big improvement in it self.

-

Side question: Whats the strategy in terms of getting tracker and blaze on npm, is it part of the general goal to make blaze more available outside Meteor again?

**Comment by mitar** [comment] 2016-11-06 09:53
> Whats the strategy in terms of getting tracker and blaze on npm, is it part of the general goal to make blaze more available outside Meteor again?

We are waiting for Tracker to be first moved to NPM: https://github.com/meteor/blaze/issues/13#issuecomment-255843440

**Comment by NitroBAY** [comment] 2016-11-09 23:09
I had another problem also, I add a template X nested into another Y. Y is a dynamic template and is called by `Blaze.render()` thanks to flowRouter. When Y is created and rendered after being destroyed previously, `Template.Y.onCreated()` and `onRendered()` are called, but X, nested into Y, has a less logical behavior. Oncreated/onrendered can be only called once but even if it's destroyed the template never have its rendered/created callback called again. Since ground:db RC6 which removed dispatch:kernel X's callback are called as expected.
It's crazy how many bugs that used to drive me mad on Meteor, actually everyone, was caused by this dispatch:kernel. It's ...  crazy.

**Comment by filipenevola** [comment] 2021-03-18 19:34
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:34 UTC
