### ISSUE TITLE
Organizing discussions around Blaze 

### ISSUE THREAD

**Issue by msavin** [meteor/blaze#127] opened 2016-09-29 14:55 UTC
One thing I think many of us are struggling with is figuring out what the state of Blaze is, what is being proposed, what has been discussed, etc.

That usually leads to a "read issue X" response - which I think may discourage people from participating because they don't want to repeat something that might have been was said.

The other option is to read all the posts, but that's not enticing as many of them are old, and the discussions are not structured well. It's worse than reading a college textbook.

Maybe the real solution is to start a Trello board, similar to what Meteor had back in the good old days:
https://trello.com/b/hjBDflxp/old-meteor-roadmap-new-roadmap-at-https-github-com-meteor-meteor-blob-devel-roadmap-md

We can have sections like [Completed, In Progress, Planned, Ideas]. The first three sections could be locked down, and the fourth one (Ideas) can allow anyone to add a card and develop a discussion around it.

**Comment by tcastelli** [comment] 2016-09-29 15:07
I also think a better organization would help to be more "updated" about what is being discussed, what is being implemented what discarted etc...
I know @mitar is not a fan of using external services because it includes extra effort to sync, but what I think could be useful is to reuse the github label system to organize a trello board for example.

So basically what I'm proposing is that when labels are set on issues, an automatic trigger (it's very easy with something like zapier) moves that issue to a specific Trello board. (Not sure if the same can be done for PRs and labels), so we have a "main set" of boards with the important issues being discussed (and they also can get voted on trello for example).

Some useful main boards could be (Under discussion, approved and waiting for implementation,  under development/doing, new proposed features, discarted features/suited for packages and confirmed bugs)

**Comment by aadamsx** [comment] 2016-09-29 17:02
> One thing I think many of us are struggling with is figuring out what the state of Blaze is, what is being proposed, what has been discussed, etc.

That is one of the reason I suggested to @mitar that using the Project feature.  I think it would help us visualize the "state" of Blaze.

For example, have a Blaze 1.# Project with the following columns for example:

Backlog
Questions
Bugs
Features
Doing
Done

**Comment by tcastelli** [comment] 2016-09-29 18:11
Thanks, I removed the other post to keep it clean and continue it here. 
I have a question with this:

> Just having a list of issues is not a high enough abstraction to get a feel for the project for some. And please don't knock us for wanting more than the minimum. ;)

After reading that I must ask, what kind of features are you missing for project management? In my opinion if let's say we use trello/gh project + github issues we can have a quite deep control. So I give you a few examples of what I'm thinking based on the list of columns yo posted on the image and common project management operations.

- Ideas/Features: Someone comes up with a nice idea for Blaze and posts an issue in github repo about it. Repo maintainers set the idea/feature label and this gets copied in the project management service colum (ideas/features/whatever). The opposite is true, if someone opens a card in the trello board, a new issue coul be generated in the repo for discussion.

-Todo(backlog)/in progress: After some talk in the idea issue(or in the trello card/slack channel) people agree that the idea is indeed nice and assign someone to be responsible for the development if possible or adds "contribuitions wanted" label. Both actions automatically move that card to the Todo column(no reponsible) or the in progress column in trello. Those columns could be private to avoid creating cards directly. 

-Bugs: After finding a bug, peope could open a issue in the repo and after it is confirmed by a maintener by setting the label "confirmed bug", a new card is created in the Todo column under trello with category "bugs".

- Planning for milestones: This is quite simple, so when an issue is assigned to a future milestone, a new category tag is added on the trello board with the version which is expected to be in (no need for a large number of columns for every version in my opinion but that's my personal taste).

- Questions: For me they should be kept as an issue in the repo and if the questions is relevant, a note on the guide should be included(through the opening of a new issue "improve x on the guide" or a direct change)

So if you are missing anything for project management that I'm not covering it would be nice to see what can be done about it. I have kept estimations and scheduling out of this, since this is quite volatile normally, especially for open source and "free time" collaborators.

**Comment by aadamsx** [comment] 2016-09-29 18:16
> In my opinion if let's say we use trello/gh project + github issues we can have a quite deep control

Exactly, which is what Github Project is, a light-weight Trello -- built in.  There's a tab at the top of this very Blaze repo called Project.  I'd like that to be filled in as I suggested before.

**Comment by tcastelli** [comment] 2016-09-29 18:22
Yes, I just don't know for sure if automation between github issues and github project can be done as easily in Zapier or similars. I recall @mitar saying he was not oposed to project management, he just wanted some sort of clarifications on how things could work and which would be the benefits of using it.

In those terms, I have described something that is quite simple to set up(at least with trello, will check about gh project) and using what he wanted(labels and millestones) let's people less used to navigate through issues see the whole picture of what is going on about Blaze (next features, what needs help, what is coming in next version, etc).

**Comment by aadamsx** [comment] 2016-09-29 18:23
> Yes, I just don't know for sure if automation between github issues and github project can be done as easily as in Trello with Zapier or similars.

Ok, maybe I missed it, what type of automations?

**Comment by tcastelli** [comment] 2016-09-29 18:31
In Zapier what you define basically is 2 or more rules from 2 services with a REST Api, so for example we create a "zap" tha has:

1st rule: Service: Github Trigger: Label on issue and label is "idea"
2nd rule: Service: Trello Action: Create a card under "idea" column with the issue link

This are all the triggers supported by Github from Zapier

> New Commit Comment
> Triggered when a new comment on a commit is created.
> New Pull Request
> Triggered when a new pull request is created.
> New Mention
> Triggers when your Github username is mentioned in a Commit, Comment, Issue or Pull Request.
> New Commit
> > Triggered when a new commit is created. Select your organization, repo and branch.
> New Issue
> New Event
> New Gist
> New Notification
> New Milestone
> New Label
> New Repository
> New Branch
> New Collaborator
> New Organization
> New Watcher
> New Team

 and this are the possible actions in github (if we change rello for github in the second rule)

Create Issue
Create Pull Request
Find Issue
Find Pull Request
Find Organization
Find User
Find Repository
Find a specific repository

So it seems that github project actions are not possible for now (with zapier at least), that's why i suggested trello 👍

**Comment by aadamsx** [comment] 2016-09-29 19:06
So with Zapier, we put a label on a Issue of some type and Trello gets a card of that type?  

Why can't we manually do this?  How hard is it -- not very.  I'd actually want more control.  What if the label changes, will it move the card to another column on the board?

Also, why not let me or someone else try to move the cards around and manage them on Github Project -- if you don't like it or it doesn't work out -- just delete it?  It doesn't cost anything to try it.

I can't help but think Github will eventually link up labels and Project -- and I don't want that valuable data outside the repo.

**Comment by tcastelli** [comment] 2016-09-29 19:13
Yes it will create the card automatically and you could define a zap for when label changes then it also moves de card to another column. This is quite practical in terms of not having anyone waste his/her time to keep both services syncronized. 

Honestly if you compromise to do that task and always have time to keep it updated, then there is no problem from my side 😆. I just proposed an alternative to make it costless since who knows what will happen to anyone of us tomorrow (so maybe you have to move/have a new project that keeps you away/etc and no one else can keep that work up)

What you said about github eventually connecting both things could be true, but there's always the option to export trello data and import it from project. Actually I never used it before since Trello is free and has a lot of integrations with different software, but I can understand the point. (Maybe something similar to Zapier allows us to do the same but with github project)

**Comment by aadamsx** [comment] 2016-09-29 19:30
> I just proposed an alternative to make it costless since who knows what will happen to anyone of us tomorrow (so maybe you have to move/have a new project that keeps you away/etc and no one else can keep that work up)

I promise, I'll try.  But you know, you're right.  I might get very busy from time to time and won't be able to manage it for a week or so.  What if I go on vacation for example.  So if it has to be 100% up to date at all times (and I have no backup), then yeah, automate it.

I was just looking for a light-weight way to contribute.

**Comment by tcastelli** [comment] 2016-09-29 19:38
Yes I know what you mean, and tbh if the size of the new issues stays relatively constant I think manually moving issues is feasible (especially if the task is shared between a few people, not only one), but just as a curiosity test, I have been trying the zapier thing to see if it would be possible (creating lists, moving based on labels, etc) and so far I managed quite a lot of things to work. I have been looking for alternatives that are integrated with github projects but no luck so far.

Anyways even if we have the automation part, we can always have the option to move them in Trello manually like you suggested. We just need to make sure that there are rules that cover card movements and they get the proper translation into zapier rules (but maybe generating those rules takes 1 day and then you are done forever)

**Comment by aadamsx** [comment] 2016-09-29 22:32
@tcastelli are you going to own that task for us then?

**Comment by aadamsx** [comment] 2016-09-29 22:35
@tcastelli also, do you know if Trello will be integrated into the Projects tab on this repo or?

**Comment by tcastelli** [comment] 2016-09-29 22:48
If more people think it is a good idea to keep a trello(or similar) I don't mind helping/setting up the configuration in flowXO. However a user with grants on this repo is needed for that.
As far as I know you can't include Trello directly in github, only the opposite is possible, so if you pay a Business Class account in Trello, you can manage directly github issues, PRs and everything else from Trello directly(without needing for external tools like zapier or flowXO).

**Comment by aadamsx** [comment] 2016-09-29 22:58
@mitar I'd like to try out Github Project in this repo.  I need permissions to do just this and nothing else.  It will not interfere with Issues or Milestones.  If someone else wants to manage Trello (like @tcastelli), that's fine too -- it also will not interfere with Github Project.

**Comment by mitar** [comment] 2016-09-30 05:31
I made one iteration at projects and categorized all current open issues into [them](https://github.com/meteor/blaze/projects). I hope this makes things clearer, but one still has to read issues to understand what some cryptic titles mean. :-)

How does it look? Is this what you had in mind? Feedback welcome.

The idea is that only open issues are in projects. So that people can see what is planned and can decide to contribute. For done issues, one should just consult [history](https://github.com/meteor/blaze/blob/master/HISTORY.md), or milestones.

We will then use milestones only to group immediate next work, so that people can see what we are focusing on. There are `Being worked on` columns in each project, but they do not group things across projects well. It is also easier to link directly to a milestone and say "can you help here". Maybe we can deprecate milestones in the future, if we see that history is enough.

@aadamsx, thank you for volunteering. I added you and I think you should have enough permissions to manage issues. I agree that for now we should just try to see how it works if we manage them manually. So please if you see any new issue, consider adding it to one of the projects first column. If you see that any issue has been worked on, move it to the last column. And if you see that anything was closed, move it out of the project.

**Comment by laosb** [comment] 2016-09-30 09:11
Willing to help on organizing Projects too! 🙌

**Comment by mitar** [comment] 2016-09-30 09:41
You can also help with programming. ;-)

**Comment by laosb** [comment] 2016-09-30 09:47
Haven't dealt with Blaze's code, but issues there sound very interesting! Is there any guidelines for contributing in code, or just align with Meteor itself?

**Comment by mitar** [comment] 2016-09-30 09:51
Yea, more or less like Meteor. :-) [Check these issues](https://github.com/meteor/blaze/labels/contributions%20welcome) for ideas what to contribute.

**Comment by laosb** [comment] 2016-09-30 10:38
Should we have a `pr-encouraged` label so we can easily filter what we can start coding on immediately?

**Comment by aadamsx** [comment] 2016-09-30 16:01
> How does it look? Is this what you had in mind? Feedback welcome.

Wow, it looks great! Yes, not exactly like this, but this really works.

> The idea is that only open issues are in projects. 

This is what I had in mind too.  Why have closed issues in projects, doesn't make sense for what Project is used for.

> For done issues, one should just consult history, or milestones.

Agreed, done issues should be kept off the Project board.  They can be handled just as before if you like.

> We will then use milestones only to group immediate next work, so that people can see what we are focusing on. 

This will work for now. What's in the next release, look to the next Milestone.

> Maybe we can deprecate milestones in the future, if we see that history is enough.

I think of Milestones as a kinda stop-gap for Projects.  They're all just grouping mechanisms in the end, but Projects just seems more dynamic and flexible.

We can use Milestones for grouping releases as you say for now, and see how things shake out later.

> I added you and I think you should have enough permissions to manage issues.

Thank you.  I'll try to stay on top of it.  If I'm going to be out for a few days, I'll let you know somehow.


 > So please if you see any new issue, consider adding it to one of the projects first column. If you see that any issue has been worked on, move it to the last column. And if you see that anything was closed, move it out of the project.

Will do!

**Comment by mitar** [comment] 2016-09-30 17:05
> Should we have a `pr-encouraged` label so we can easily filter what we can start coding on immediately?

We have it. It is called [`contributions welcome`](https://github.com/meteor/blaze/labels/contributions%20welcome).

**Comment by mitar** [comment] 2016-09-30 18:28
> Thank you. I'll try to stay on top of it. If I'm going to be out for a few days, I'll let you know somehow.

Don't worry. I think nothing bad will happen if you are not immediately responding. Do not get stressed over this.

**Comment by aadamsx** [comment] 2016-09-30 18:31
> Don't worry. I think nothing bad will happen if you are not immediately responding. Do not get stressed over this.

Sounds good.

**Comment by mitar** [comment] 2017-01-06 22:26
So we have now Github projects. I have not seen that it would improve community involvement a lot, but let's keep them. I think we can close this issue now?

**Closed by mitar** 2017-01-06 22:26 UTC
Labels: discussion

**Comment by mitar** [comment] 2017-01-06 22:37
@aadamsx and others, if you have time, there ere some new issues created recently, when migrated from Meteor repository, it would be great if they could be categorized into projects as well (mostly probably as bugs). If anyone needs permissions to do so, tell me.
