### ISSUE TITLE
Template helpers rerun when data context remains the same

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#169] opened 2016-11-18 19:08 UTC
Migrating this over from meteor/meteor#3966. 

----

(originally reported by @hpx7)

Steps to reproduce:

1. git clone [https://github.com/hpx7/meteor-refiring-issue.git]()
2. click the button
3. helpers fired will be printed to the console

In the case of

```handlebars
{{#with myObject}}
  {{> hello}}
{{/with}}
```

helpers inside the hello template shouldn't rerun if myObject is recomputed but the new value returned by the helper is the same as the old one.

Note that this works correctly (no re-firing) with `#if` instead of `#with`.

**Comment by mitar** [comment] 2016-11-18 20:26
I think this is a duplicate of #68.

**Closed by mitar** 2016-11-18 20:26 UTC
