### ISSUE TITLE
Blaze: Uncaught Error: Must be attached

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#213] opened 2016-12-13 14:12 UTC
Migrating this over from meteor/meteor#2981.

----

(originally reported by @mitar)

See [example project](https://github.com/mitar/meteor-issue2981). When clicking on "Click Me" button, there is an uncaught Error: `Must be attached`.

```
Uncaught Error: Must be attached domrange.js:337
DOMRange.containsElement domrange.js:337
(anonymous function) view.js:741
(anonymous function) events.js:47
jQuery.event.dispatch jquery.js:4624
elemData.handle jquery.js:4292
```

**Comment by bastiW** [comment] 2017-01-02 15:06
is there any workaround for this?

**Comment by mitar** [comment] 2017-01-02 15:21
Yes, [see discussion here](https://github.com/meteor/meteor/issues/2981#issuecomment-87654677).

**Comment by aadamsx** [comment] 2017-01-10 14:52
Ha, I just ran into this for the first time today!

**Comment by rtcwp07** [comment] 2018-05-05 19:06
I'm probably the last person still using Blaze, but for posterity I will add here that I encountered this error when I was using jQuery to get a field value for a method call, and solved it by making sure that I used the template.$ jQuery call instead.

**Comment by dariovillalta** [comment] 2018-05-06 22:27
@rtcwp07 cheers man, could you please elaborate what you mean with "the template.$ jQuery call"? Thanks!

**Comment by dariovillalta** [comment] 2018-05-22 02:49
@dr-dimitru nice explaining, thank you so much!

**Comment by snajjar** [comment] 2020-07-23 13:01
No update after 2 years? This keeps happening a lot (I use external libraries that are based on jquery)...

**Comment by filipenevola** [comment] 2021-03-18 19:39
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:39 UTC
Labels: bug, contributions welcome

**Comment by lynchem** [comment] 2021-12-01 17:37
I think this is worth reopening @filipenevola  as it's still happening a LOT and it would be a shame to lose all the history. It's already been evicted once. 

I don't see anything relating to jquery in the callstack for our project. The two most common call stacks I see are as follows: 


> Error: Must be attached
>     at meteor://💻app/packages/blaze/domrange.js:191:10
>     at firstNode (meteor://💻app/packages/blaze/template.js:171:38)
>     at _currentTemplateInstanceFunc (meteor://💻app/packages/blaze/template.js:559:16)
>     our code
>     at apply (meteor://💻app/imports/startup/client/blaze-exceptions.js:13:21)
>     at apply (meteor://💻app/packages/blaze/exceptions.js:51:15)
>     at apply (meteor://💻app/imports/startup/client/blaze-exceptions.js:29:58)
>     at func (meteor://💻app/packages/blaze/template.js:490:13)
>     at _withTemplateInstanceFunc (meteor://💻app/imports/startup/client/blaze-exceptions.js:28:30)
>     at apply (meteor://💻app/packages/spacebars.js:172:17)
> 


> 
> Error: Must be attached
>     at meteor://💻app/packages/blaze/domrange.js:337:10
>     at containsElement (meteor://💻app/packages/blaze/view.js:890:24)
>     at apply (meteor://💻app/packages/blaze/events.js:47:23)
>     at apply (meteor://💻app/packages/modules.js:30617:26)
>     at apply (meteor://💻app/packages/modules.js:30429:27)

**Comment by distalx** [comment] 2022-01-16 00:48
I also recently saw this in my project. 
For me workaround was to renaming few of the selectors. 
```js
domrange.js:337 Uncaught Error: Must be attached
    at Blaze._DOMRange.DOMRange.containsElement (domrange.js:337:11)
    at Blaze._DOMRange.<anonymous> (view.js:891:25)
    at HTMLButtonElement.<anonymous> (events.js:49:24)
    at HTMLDivElement.dispatch (modules.js?hash=5a94ac1782b4de33da07a5edf5fbaede26f5d256:20544:27)
    at HTMLDivElement.elemData.handle (modules.js?hash=5a94ac1782b4de33da07a5edf5fbaede26f5d256:20348:28)
```

**Comment by dr-dimitru** [comment] 2022-01-16 21:29
@distalx can you give an example of the selector you have renamed?

**Comment by distalx** [comment] 2022-01-17 22:25
@dr-dimitru Something like `primary-action` to `primary_action`. !!

**Comment by lynchem** [comment] 2022-01-18 09:52
So @distalx , have you managed to get rid of this completely by renaming the button class or id in question. 
So if this works does that mean there's some special treatment of hyphens in the code at some point? Seems odd.

**Comment by distalx** [comment] 2022-01-23 06:35
@lynchem, it also seem odd to me. So I've put-together a reproduction for this issue. 

https://github.com/distalx/meteor-blaze-issue-213

I believe this error occurs when a  parent and a child template both using a same selector-name.

**Comment by jankapunkt** [comment] 2022-04-14 07:07
Maybe related PR: https://github.com/meteor/blaze/pull/366

**Comment by harryadel** [comment] 2022-06-09 19:22
So, I've dug deeper into this bug. If both the parent template and child template contain an event handler that triggers on an element that *exists in both templates*, it seems only natural for it to trigger **twice**. It triggers in the child component first then once again the parent.

In the case of @distalx example repo, we get `Uncaught Error: Must be attached` because the event handler destroys the whole view via `FlowRouter.go('/')` in the child template first so when it triggers again in the parent component it cannot find the HTML/view that's accompanied to it although the event is already triggered! 

```js
<template name="parent_template">

  {{!-- The below button renders for specific case --}}
  {{!-- that logic is not important for this reproduction --}}
  <button type="button" class="go-back" name="button" hidden>
    Go back
  </button>
  {{> Template.dynamic template=child_template}}
</template>

Template.parent_template.events({
  'click .go-back'(event, instance) {
    console.log("PARENT TEMPLATE")
    event.preventDefault()
    history.back()
  },
})  	
```

```js
<template name="child_template">
  <button type="button" class="go-back" name="button">
    Go back
  </button>
</template>


Template.child_template.events({
  'click .go-back'(event) {
    console.log("CHILD TEMPLATE")
    event.preventDefault();
    FlowRouter.go('/')
  }
});	
```
I'm kind of confused as to how we can "solve" this, because the error is kind of right. You're double-triggering an event that destroys the view so of course it's gonna error in the second time. 

We can place a check [here](https://github.com/meteor/blaze/blob/master/packages/blaze/events.js#L49) to detect this (regardless of how we do it) and exit the process but I'm unsure whether this is the best route because like I said it's not a bug per se, what if this is purposeful? A developer wants to double trigger an event on both the parent and child?? It's pretty weird. I really need your opinion guys.

**Comment by dr-dimitru** [comment] 2022-06-13 09:40
> We may also modify this error so it's more telling of what's going on like event "click .go-back" on "parent_template" triggered but no attached view is found., so developers can tell which event/template caused this error and can modify it.

Sounds like the most appropriate solution

**Comment by harryadel** [comment] 2022-06-14 13:42
Thank you Dimitry for chiming in. That's one vote down for editing the error message. I need more votes to decided on this.
cc @StorytellerCZ @distalx @jankapunkt @lynchem

**Comment by lynchem** [comment] 2022-06-14 16:39
Oh wow, great work @distalx & @harryadel for debugging that 👏🏻 
Yes, I think that's the best course of action. Knowing the selector would let us track that down in our code and fix things 👍🏻
