### ISSUE TITLE
Create standalone npm package(s)

### ISSUE THREAD

**Issue by zol** [meteor/blaze#11] opened 2016-03-04 01:35 UTC
It would be fantastic if Blaze had a life of it's own and could be used independently like React. I'm sure there are a lot of details to work out, some of them potentially difficult (e.g dealing with assumptions on globals). 

I wonder if it's feasible to create a Webpack [loader](https://webpack.github.io/docs/loaders.html) that loads `.blaze.html` files.

**Comment by rclai** [comment] 2016-03-05 19:16
Someone actually made a spacebars loader plugin for webpack and I've used it briefly: https://github.com/xamfoo/spacebars-loader

**Comment by stubailo** [comment] 2016-03-05 19:39
Ooh, that's awesome!

**Comment by mitar** [comment] 2016-03-05 20:15
cc @xamfoo

**Comment by rclai** [comment] 2016-03-06 00:13
@murillo128 would you be interested in helping out with this?

**Comment by murillo128** [comment] 2016-03-06 00:52
hi all!

In fact we already did that!

https://github.com/eface2face/meteor-client/blob/master/README.md

We have not keep up to date with latest meteor versions mainly because it is working like a charm for us in several production projects.

Shouldn't be much of an issue to update it to latest one.

**Comment by murillo128** [comment] 2016-03-06 00:55
Also, as a bonus we created a jQuery  plugin (https://github.com/eface2face/jquery-meteor-blaze/blob/master/README.md) for old school guys like me ;)

**Comment by mitar** [comment] 2016-03-06 00:57
Would you be interested in bringing this upstream into the official package?

Also, how are you doing HTML files processing?

**Comment by murillo128** [comment] 2016-03-06 01:10
With this:
https://github.com/eface2face/jquery-widget-compiler/blob/master/README.md

We are using our "home made web components" based on jQuery widgets (you know, old school). We process the html, parse the html generating the js for each template, and bundling it together.

**Comment by murillo128** [comment] 2016-03-06 01:11
And for sure we would be interested to collaborate and get this into the official package

**Comment by mitar** [comment] 2016-03-06 01:11
I think that would be a great one way to do it. But also compilation on the server side would be great. Maybe server side should use webpack and client side should use jQuery. That would be an amazing first iteration.

**Comment by murillo128** [comment] 2016-03-06 01:17
I don't have any experience/knowledge of webpack, I would have to check what is about.

But either using raw meteor blaze functions, or the plugin, all you need is the js function for the template generated by the spacebar compiler.

But as the spacebar compiler is also an npm package, you can generate it on the server side without issues.

**Comment by mitar** [comment] 2016-03-06 01:27
Oh, don't worry. Everyone would contribute what they know. I am just describing broader plan. It seems you @murillo128 have experience with the client side and jQuery, and @xamfoo with webpack. Together we could do something good.

**Comment by xamfoo** [comment] 2016-03-06 01:51
I'll love to help!

@murillo128 Thanks for your work on the npm packages.

For a start I'll update my repo and add some tests for the current Blaze version.

I'm curious to see where this is going :)

**Comment by mitar** [comment] 2016-03-06 01:54
Any suggestions how to make NPM module which can compile server-side HTML files into something which can then be available on the client side?

**Comment by stubailo** [comment] 2016-03-06 01:57
We should look into what React, Vue, and Ember provide for build plugins.

**Comment by xamfoo** [comment] 2016-03-06 07:38
> Any suggestions how to make NPM module which can compile server-side HTML files into something which can then be available on the client side?

@mitar Would you be talking about on-the-fly compilation of html files? Webpack only does HTML-to-JS conversion at compile time.

**Comment by mitar** [comment] 2016-03-06 07:57
No, but compilation time as well. Like Meteor does currently. And then pushes compiled templates as JavaScript to the client.

**Comment by murillo128** [comment] 2016-03-06 09:28
btw, we also did that already! hehehe

https://github.com/eface2face/spacebars-compiler

It can be used by gulp/webpack scripts to generate .js with the template functions from the .html files. It has also a bin executable to run it standalone.

**Comment by mitar** [comment] 2016-03-06 09:29
Amazing! Really good stuff.

**Comment by mitar** [comment] 2016-03-06 09:30
I would propose that we make official packages NPM packages by default, which can be browserified for the client. And then for Meteor we just wrap them as Meteor packages wrapping NPM (to keep backwards compatibility and hooking into Meteor tool-chain).

**Comment by murillo128** [comment] 2016-03-06 09:34
In order to generate all the npm modules/git repositories of each meteor module, we used this project, so it was easy for us to keep up to date with meteor code until we got an stable version for us:

https://github.com/eface2face/meteor-module-generator

It retrieves original meteor source code, and for each module, we have concatenate the files in it, adding a header and a footer in order to add the module.export, closures, and get the references to the other modules as required.

We tried to not touch any meteor code, so it could be as "original" as possible. I am sure that there has been quite some changes in meteor code, but updating it to work again should not be so difficult.

I could create a branch on it to start the work on it.

**Comment by murillo128** [comment] 2016-03-06 09:39
BTW, I only converted the modules strictly needed for Blaze in order to reduce end size. IIRC I did some trick and moved some functions from Observable sequence to another module so i could reduce 1mb the final file, but apart of that everything is 1-to-1 meteor vanilla code.

I will create on monday an example project on how to use the spacebar-compiler and jquery plugin (with gulp).

**Comment by stubailo** [comment] 2016-03-06 19:34
This is amazing! It will be great to get all of this work back in one place.

**Comment by murillo128** [comment] 2016-03-07 11:23
Hi all,

I created a simple repository with an example of usage of the spacebars-compiler inside a gulp file to convert the .hbs template files to a .js file containing the compiled template functions.

Then the app loads the resulting .js file and uses it with the jquery-meteor-plugin (they could be used with the raw Meteor blaze functions as well):

https://github.com/eface2face/jquery-meteor-blaze-example

**Comment by zol** [comment] 2016-03-07 21:28
Wow, this is great - I had no idea folks were already working in this direction. It would be great if this repo could became the integration point of these projects.

**Comment by mitar** [comment] 2016-03-07 21:32
See, what happens when you open development for the community. ;-)

I think we should also think about how to improve testing and documentation. Because this will be new things which will have to be documented somewhere extra. Because this use cases (using as NPM stand-alone) is not something which would be part of the documentation included in Meteor documentation). Maybe for now we can just have a very long `README.md` file in the root of the project. And then later on we decide to host it better.

**Comment by stubailo** [comment] 2016-03-07 22:38
> Maybe for now we can just have a very long README.md file in the root of the project. And then later on we decide to host it better.

I think @martijnwalraven and @tmeasday have been thinking about how to take these READMEs and inline them into docs.meteor.com. There are also countless docs hosting services like readme.io and readthedocs that can make stuff more readable in the meanwhile.

**Comment by mitar** [comment] 2016-03-07 22:44
If somebody makes readthedocs work for node.js, I am all ears. I need that for some other projects. Currently I just use Travis CI + git push onto gh-pages branch and it works pretty well:
 * https://peerlibrary.github.io/meteor-blaze-common-component/
 * https://github.com/peerlibrary/meteor-blaze-common-component
 * https://github.com/peerlibrary/meteor-blaze-common-component/tree/gh-pages

**Comment by stubailo** [comment] 2016-03-07 22:52
> If somebody makes readthedocs work for node.js

What about the documentation site is related to node? You mean like using JSDoc for generated docs?

**Comment by mitar** [comment] 2016-03-07 22:58
To my knowledge readthedocs requires Python and Sphinx or Markdown.

For JSDoc I would just use Travis CI to run it at the end of the testing phase and push it to the GitHub static pages.

**Comment by stubailo** [comment] 2016-03-07 23:08
Yeah sure, I don't think it really matters what we use. For example we could just have a GitHub pages template for package documentation that we share across all the packages. But a README is a fine start.

**Comment by mitar** [comment] 2016-03-07 23:11
Agreed. I proposed README just to have somewhere to document how to use all those NPM things. We can later on think about better systems.

**Comment by murillo128** [comment] 2016-03-09 18:33
Hi guys!

I have created a branch of my meteor-module-generator to get in sync with latest meteor code:

https://github.com/eface2face/meteor-module-generator/tree/meteor-update

The good news are that everything is mostly working (I just need to manually change a "...seeds" to avoid having to use babel to transpile to ES5).

I even have added tests to it, and got a good part of them working. If you want to test it, just get the broserified output here:

https://github.com/eface2face/meteor-module-generator/tree/meteor-update/test

I will post tomorrow the instructions to how to reproduce the results, but mainly they are:
*checkout meteor-module-generator branch meteor-update
*checkout latest meteor code under meteor submodule 
*run modules/build.sh
*manually modify the meteor-ramdon/dist file to remove the ...
* browserify test.js -o test/test.bundle.js

**Comment by mitar** [comment] 2016-03-09 21:31
Great job!

I would propose the following plan:
* we get CircleCI tests running for this repository
* then we work on changing this repository so that all code is inside NPM packages
* we change Meteor packages to simply include those NPM packages and wrap them
* through the process we make sure tests are passing (this means we are keeping backwards compatibility with Meteor)

In this way we would not really need to maintain a script to convert Meteor packages to NPM. We just do it once and from then on this is it.

Alternatively, we could just make so that code is separate from packaging all together and then we just provide various types of packaging (NPM, client-bundle, webpack, Meteor).

**Comment by stubailo** [comment] 2016-03-09 21:32
This sounds like an ideal approach.

**Comment by mitar** [comment] 2016-03-09 21:35
Which one, first plan or an alternative? (I think alternative might be a bit more work initially, but could be better in the longer term.)

**Comment by martijnwalraven** [comment] 2016-03-09 21:42
One thing we may want to think about is how to support ES2015 modules in these NPM packages. Ideally, we'd be able to provide an ES2015 entrypoint with `jsnext:main` in addition to CommonJS.

**Comment by martijnwalraven** [comment] 2016-03-09 21:48
Also, is the idea still to allow code to be written in ES2015 and transpiled using Babel? I personally wouldn't want to go back to ES5 :)

**Comment by mitar** [comment] 2016-03-09 21:50
Does any of the code in this repository uses ES2015? I do not think so (except for small part of random package). But yes, we can do a more complicated build process if we really want. We could also hook building into CircleCI runs, so that we can have a directory `dist` which provides bundled JavaScript file for direct inclusion with `<script>` tag.

**Comment by mitar** [comment] 2016-03-09 21:51
> One thing we may want to think about is how to support ES2015 modules in these NPM packages. 

Yes, this is then the idea of the alternative approach. My issue is that this will require more work. So maybe we should just do and convert to NPM packages, because this is what @murillo128 already did and has experience. And then we have another iteration of making it even better later on.

**Comment by murillo128** [comment] 2016-03-09 22:03
AFAIK, only one line of code needs to be changed on random, so IMHO it is better to get it back to ES5 , than using Babel.

One thing to take into account is that we have only ported the client side is files and only the packages needed for blaze (no minimongo, no dsl). Shouldn't be much of an issue, but lots of work more needed. That's why tests must be run on a browser.

Other thing is that due to our requirements, we are not exporting anything to window/global so all references are kept inside the main Meteor object ( like Meteor.Blaze).

Last thing is that we are no way experts in node, in fact this was our first project we used that. So we may need to improve how we do the exports/requires. The goods news are that we have just to think it it once and then apply same pattern everywhere..

**Comment by mitar** [comment] 2016-03-09 22:09
For now we are looking only into making Blaze work stand-alone, so do not worry about our Meteor packages (if they are not a dependency for Blaze to work).

> we are not exporting anything to window/global so all references are kept inside the main Meteor object

I would not even keep it inside Meteor object, but simply allow export/import and then you can import Blaze symbol as needed. For NPM packages.

Or are you talking for `<script>` tag file? For those I would export globally to `window` symbol `Blaze`, because this is a stand-alone package, no?

**Comment by martijnwalraven** [comment] 2016-03-09 22:10
I think the question is what we mean by converting the code in this repository to NPM packages. In @murillo128's model, the NPM packages are the output of a build script, which is great if you're concerned with consuming these packages, but I don't think you'd want to take that as a starting point for continued development. If you look at [`blaze.js`](https://github.com/eface2face/meteor-blaze/blob/master/blaze.js) for instance, you now have a single concatenated bundle instead of the separate files that make up the `blaze` package source.

I think continuing development by converting the code in this repository to use proper ES2015 modules and imports/exports would be much more future proof.

**Comment by murillo128** [comment] 2016-03-09 22:10
Regarding the path to follow I think it would be easier to just have npm packages ( if meteor supports to work with them nicely). That seems to be the industry standard lately.

**Comment by mitar** [comment] 2016-03-09 22:18
@martijnwalraven: That's what I proposed above. My question is:
* do we just convert it to (nice) NPM packages (so not directly the output of @murillo128's scripts) with thin Meteor packages around for Meteor compatibility, or
* do we take extra effort now and do all ES2015 imports/exports and then do various packaging, Meteor and NPM among them

I think we should start with the first (so ES5, no imports exports, NPM imports/exports). And then in next iteration we move away from there.

**Comment by martijnwalraven** [comment] 2016-03-09 22:24
But what do you mean by nice NPM packages? As I understand it, the issue is that the files making up these packages depend on Meteor's scoping rules and the exports specified in `package.js`. So that makes it hard to convert that to module systems like CommonJS outside of the Meteor build tool. 

So converting to ES2015 import/export and `api.mainModule` could actually be a first step towards breaking the dependency on the build tool.

**Comment by murillo128** [comment] 2016-03-09 22:35
I kind of agree with @martijnwalraven, and in fact i was thinking about the same problem.

AFAIK, node exports create its own javascript closure, so you can only access the exported variables/objects/functions. From my experience, js files on meteor seems to depend to much of running on same closure than the other ones in the same directory. That's why I need to concatenate them all together, and then export just one object.

So in order to make create "nice" npm packages it would create quite a lot of effort to refactor meteor's code or at least moving code around between different files.

IMHO (obviously I am biased) it is not an issue to not have not-nice npm packages.

**Comment by martijnwalraven** [comment] 2016-03-09 22:37
> IMHO (obviously I am biased) it is not an issue to not have not-nice npm packages.

That may be true if the goal is only to consume the packages, but I don't think you'd want to continue development on those concatenated files.

**Comment by murillo128** [comment] 2016-03-09 22:38
> That may be true if the goal is only to consume the packages, but I don't think you'd want to continue development on those concatenated files.

Completely agree.

**Comment by mitar** [comment] 2016-03-09 22:48
> But what do you mean by nice NPM packages?

Convert to nice NPM packages means changing current Meteor code to use node.js `exports` and `require`. Files are still split into multiple files.

Then we have NPM packages and then we use Meteor `Npm.require` to get them in and expose them through Meteor.

This is the proposal 1).

The proposal 2) is to convert code to ES2015 and go from there to NPM, Meteor and so on. I think it will be more work, but it is probably long term better.

I am proposing that we first go with 1) and then go to 2) later on.

**Comment by martijnwalraven** [comment] 2016-03-09 22:58
> I am proposing that we first go with 1) and then go to 2) later on.

I can see how that would be a better way of getting something out quickly.

**Comment by murillo128** [comment] 2016-03-09 23:15
1) would require quite some intense work anyway. Take blaze package for example.

Do node-way of doing things would be to move each object to a file. So we would have

var Blaze = require('./blaze.js');
var DomRange = require('./domrange.js');
var ElementAttributesUpdater = require('./elementattributesupdater.js');

module.exports = Blaze;
...

Currently, in blaze project, some files contain more than one object definition, and some objects are split into more than one file, with cross references.

So, maybe, it could be easier to do 1a) and 1b) that's it:
* merge all files into one and publish npm, ensure everything is working
* iterate and extract each object into it's own file

I thing that would be much easier (and straight-through) than having to look at several files simultaneously to look every place an object is referenced, and also take care of global variables and "var" definitions to reshuffle code.

Also, this approach would allow to keep updating the code from meteor main repository while we do the migration. If we start making changes on the file structure, backporting changes from meteor main repo could be a nightmare (that's why i created the scripts, not to have to do it manually :)

**Comment by martijnwalraven** [comment] 2016-03-09 23:18
> Also, this approach would allow to keep updating the code from meteor main repository while we do the migration. If we start making changes on the file structure, backporting changes from meteor main repo could be a nightmare (that's why i created the scripts, not to have to do it manually :)

But the whole point of this repository is to be able to remove the Blaze packages from the main repository. We're planning on doing that right after 1.3. So there is no backporting, this repository is the canonical source for Blaze.

**Comment by murillo128** [comment] 2016-03-09 23:26
Are you going also to move the following packages?

Meteor
Meteor.Base64
Meteor.EJSON
Meteor.Random
Meteor.MongoID
Meteor.IdMap
Meteor.OrderedDict
Meteor.Tracker
Meteor.ObserveSequence
Meteor.HTMLJS
Meteor.HMLTools
Meteor.ReactiveVar
Meteor.Blaze
Meteor.BlazeTools
Meteor.Templating
Meteor.Spacebars
Meteor.SpacebarsCompiler

I needed all of them in order to have Blaze properly working, and all of them need to be a npm package

**Comment by mitar** [comment] 2016-03-09 23:28
Yes. This is what we are talking in #13.

`Meteor` will probably not be moved, just those few functions from there should probably be moved.

Some other dependencies are very light and could probably first be split and then used.

**Comment by murillo128** [comment] 2016-03-09 23:36
What I think that we are in agreement is how the final repository should look like. Now we only have to decide which approach to take if, making an initial "merged" commit, and then split, or do the work "on the background" and commit the final result.

For me, if I had to do the job, i would prefer splitting from a merged file, and then go extracting code little by little. Also it has the benefit that we could have initial repos ready on 1.3+1 hour.

**Comment by mitar** [comment] 2016-03-09 23:52
I do not think a merged commit would really be useful. I do not know which IDE you are using, but Webstorm really nicely helps with telling you what is where and there is also grep/find. I do not think it is too hard to find in which files things are and make sure exports work well. Also, it is pretty obvious when you forget something.

My intuition is also that most files are already nice separation. Maybe some files are just too big and would have to be split even more. This is why I would start with existing files.

**Comment by martijnwalraven** [comment] 2016-03-10 06:36
Yeah, I would advise against starting from the concatenated files you get as part of the build script. The existing file organization can certainly be improved, but I think you can do that bit by bit. You would also lose the commit history, which is still an important source of information on what was changed and why.

I I were to do this (which I'm not :smile:), I would probably also want to take the opportunity to convert the code to ES2015. Not just to modules, but also using class syntax and other syntactic improvements that make the code more readable.

That would mean you'd need to use a build tool that includes a Babel transpilation step. But that seems worth it to me and also seems to be the direction most JavaScript projects are moving into.

**Comment by murillo128** [comment] 2016-03-10 09:20
The problem is that current file architecture does not play well with node. 

For example, I analyzed the files from blaze package and found this:
 * preamble.js  -> this should be moved to blaze.js
 * dombackend.js -> this is fine
 * domrange.js -> this is fine
 * events.js -> this is fine, maybe rename to eventsupport to match exported name
 * attrs.js -> This is fine, maybe rename to attributehandler to match exported name
 * materializer.js -> this should be merged into blaze.js
 * exceptions.js -> this should be merged into blaze.js
 * view.js  -> this is fine
 * builtins.js -> this should be merged into blaze.js
 * lookup.js -> this should be merged into blaze.js
 * template.js -> this is fine

So the final structure would look like:
 * blaze.js
 * dombackend.js
 * domrange.js
 * eventsupport.js
 * attributehandler.js
 * view.js
 * template.js

Anyway, as I am the most probable candidate for doing it, it is a bit irrelevant how I perform the task, as long as the final commit is a "nice npm" package.. ;)

What worries me more is about the code shared with meteor, that's it:

 * meteor-core
 * random
 * ejson
 * id-map
 * mongo-id
 * observe-sequence, and ordedered-dict??

How do you plan to handle them? I would discourage to have duplicate code, but we need then as npm packages.

On a more prosaic topic, we need the npm package names, and blaze is already registerd. I have the following ones:

https://www.npmjs.com/~sgarcia

If you are fine, I can transfer them to you (not sure how it is done) and we can reuse them.

Couple of questions more, when is 1.3 release due date? Do you plan to have blaze release numbers same as meteor ones? (If we reuse my names we should give them a mayor version bump and start with 2.0.0)

**Comment by mitar** [comment] 2016-03-10 09:22
> Anyway, as I am the most probable candidate for doing it, it is a bit irrelevant how I perform the task, as long as the final commit is a "nice npm" package.. ;)

And git history is kept as much as possible. ;-)

**Comment by mitar** [comment] 2016-03-10 09:23
> How do you plan to handle them? I would discourage to have duplicate code, but we need then as npm packages.

Yes, they will also have to be extracted from core. Can you list precise list of which additional packages has to be moved out of core Meteor repository in #13? Also, check what exactly is used from `meteor-core`.

**Comment by mitar** [comment] 2016-03-10 09:24
For name, maybe `blazejs`?

**Comment by murillo128** [comment] 2016-03-10 09:36
The list is the one below:

- Core
- Base64
- EJSON
- Random
- MongoID
- IdMap
- OrderedDict
- Tracker
- ObserveSequence <- will have to double check this
- HTMLJS
- HMLTools
- ReactiveVar
- Blaze
- BlazeTools
- Templating
- Spacebars
- SpacebarsCompiler

I think ```meteor-core``` is widely used, would be a huge task to know exactly which tiny bits are used or not. At least manually.

Regarding npm packages, I have kept a 1-to-1 relation between meteor package and npm packages, not sure if it is really needed now and maybe we could just get one ```blazejs``` one. I would have to check.

**Comment by mitar** [comment] 2016-03-10 09:40
Please make this list in #13.

**Comment by luisherranz** [comment] 2016-03-16 11:05
I have to say this looks excellent @murillo128

**Comment by murillo128** [comment] 2016-03-29 14:31
FWIW I have updated my packages with Meteor Release 1.3:

https://github.com/eface2face/meteor-client/blob/master/README.md

I have also added more tests from the official meteor pacakage (https://github.com/eface2face/meteor-module-generator/blob/master/test.js) and they are all passing OK (except the startup one as i didn't include it on meteor-core). You can run them on your own here: https://jsfiddle.net/Los50vhs/

**Comment by mitar** [comment] 2016-08-29 03:05
I am moving this issue to a later milestone. For now we are going with Meteor-only packages. But once there will be a clearer picture how to make a NPM module to process templates, we should move to that. Feel free to comment here and suggest ideas how to do it.

**Comment by stubailo** [comment] 2016-08-29 05:58
I agree that first steps should just be with Meteor/Atmosphere packages, but in the future I think it could be fine to have everything on npm except the compiler integration, which should probably just load an npm package that actually does string processing internally. Although ideally at some point the Meteor tool will support npm build plugins as well.

**Comment by murillo128** [comment] 2016-08-29 07:34
With all the due respects, the last commit was on March 10th. Postponing the decision on how to move forward (even if it is a bad one), will definitively kill Blaze IMHO.

**Comment by stubailo** [comment] 2016-08-29 07:56
> Postponing the decision on how to move forward

There's a decision now: publish Meteor packages.

**Comment by mitar** [comment] 2016-08-29 08:11
Yes, the plan is for now to release few versions as a community with Atmosphere. (It is now time for community to start making pull requests.) Also, if anyone wants to tackle NPM and other integrations that would be awesome. But I just want to just organize issues a bit. But in general I think the process of development of Blaze will be more or less depending on pull requests.

**Comment by murillo128** [comment] 2016-08-29 08:11
IMHO that is a NoOp ;)

From my point of view, moving Blaze to an independent npm package allowed it to have live beyond Meteor and be evolved more dynamically.  As Meteor is adding more popular/hype rendering options (mainly React) I would foresee that the interest in Blaze is going to drop significantly.

**Comment by mitar** [comment] 2016-08-29 08:15
OK. So, feel free to make a pull request moving to NPM. I think we could extract Blaze to it, and then use compiler plugin from Meteor package only, like @stubailo wrote above.

The issue with NPM is that there are also dependencies. Like Tracker. Then we have to move those to NPM as well.

@stubailo, what should we do with those packages? Would MDG be interested in moving them to NPM and then providing just thin backwards compatibility Meteor packages?

**Comment by murillo128** [comment] 2016-08-29 08:53
As you say, I can't make any PR to move to npm as it requires Meteor dependencies that are not on npm. So this is kind of stale mate ;)

**Comment by mitar** [comment] 2016-08-29 09:09
OK, @stubailo, @tmeasday, what do you think? Could we move Blaze dependencies to NPM?

**Comment by stubailo** [comment] 2016-08-29 19:49
@mitar Yeah I think it could be cool to have `tracker` on Atmosphere just be a simple package that `Npm.depends` on `tracker` from `npm`. Do you have an idea of the full list of Meteor packages that would need to move to `npm` to make this work? Is it 2? 10? 50?

**Comment by tmeasday** [comment] 2016-08-29 23:22
@stubailo I looked at this once before; if I recall correctly, it's about 10.

**Comment by tmeasday** [comment] 2016-08-29 23:24
It would definitely make sense to start with Tracker, given it has no dependencies of it's own. I don't know if there are implications for the tool in having a isopacket (i.e. used by the tool) dependency moved to npm and out of core, but I think it will only be good.

**Comment by mitar** [comment] 2016-08-29 23:40
Does MDG already created [scope](https://docs.npmjs.com/misc/scope) for `meteor`? I think it would be great to have all packages under `meteor` or `mdg`. Then `mdg` packages from Atmosphere could have 1:1 names under `mdg` or `meteor` scope on NPM. So `mdg:blaze` could be `@mdg/blaze` on NPM.

BTW, `blaze` is on Atmosphere as `blaze` only, not `meteor:blaze` or `mdg:blaze`. It would be really great if all packages would be somehow resolved.

Then maybe it is better that `blaze` is mapped to `@meteor/blaze` on NPM. And `mdg:<package>` to `@mdg/<package>`.

**Comment by tmeasday** [comment] 2016-08-30 01:30
I think scopes are associated with npm usernames, so we have https://www.npmjs.com/~mdg

**Comment by mitar** [comment] 2016-08-30 01:39
They [support organizations now](https://docs.npmjs.com/orgs/setup#migrating-an-existing-username-to-an-org). I think we should consider making an organization. It can then have teams (like `blazecommunity`) and so on.

**Comment by mitar** [comment] 2016-08-30 01:39
You can create [organization here](https://www.npmjs.com/org/create). See that it asks you for scope as well.

**Comment by mitar** [comment] 2016-08-30 01:40
(Both `@meteor` and `@mdg` scopes are already used. I hope you have them.)

**Comment by mitar** [comment] 2016-08-30 01:44
Let me ask in other way: how we will get access to publish to those scoped packages? So I suggest we move for example Tracker to `@mdg/tracker` then first. How can community get permission to do so?

**Comment by tmeasday** [comment] 2016-08-30 01:57
I think you are right that we should create an organization and do the access control thing. Like I said above, we have `mdg` but not `meteor`. I might wait for @benjamn to come back from leave before doing this as he is the one that commonly publishes the mdg-owned packages.

**Comment by mitar** [comment] 2016-08-30 02:00
Have you seen [their instructions about names](https://www.npmjs.com/policies/disputes)? It seems @substack [has currently meteor package](https://www.npmjs.com/package/meteor) which seems like a very old version of Meteor. I think you should consider asking him to give it to you to maintain now that Meteor is moving to NPM.

Not sure how to see who has `meteor` scope.

**Comment by tmeasday** [comment] 2016-08-30 02:02
I think we could get the `meteor` package, and it might be worth doing when we move the build tool across to npm.

The username is owned by some dude: https://www.npmjs.com/%7Emeteor. I'm not sure how easy it would be to get it, TBH.

**Comment by mitar** [comment] 2016-08-30 22:45
OK, so for action items about the NPM dependencies (which is more suitable for #13 issue, BTW) I see two things we need from MDG:
* team access to be able to publish under `@mdg` scope
* see if we can get `@meteor` scope (not a requirement)
* OK from you to port also those dependencies to NPM and make pull request against `meteor/meteor` repository
* in which repositories should those dependencies be? leave them in `meteor/meteor`?

**Comment by tmeasday** [comment] 2016-08-30 22:52
Thanks for the punchlist @mitar. I'm going to try and resolve these questions over the next week once @benjamn returns.

**Comment by acidsound** [comment] 2016-09-06 16:36
How about ```meteorjs```? this user name is still available.

**Comment by murillo128** [comment] 2016-09-08 08:01
FWIW, I have the following names already registered on npm and would be willing to transfer them:

```
meteor-base64 - v1.3.0
meteor-blaze - v1.5.0
meteor-blaze-tools - v1.5.0
meteor-client - v1.3.1 - Meteor client libraries
meteor-core - v1.3.1
meteor-diff-sequence - v1.3.1
meteor-ejson-safe - v1.3.0
meteor-htmljs - v1.5.0
meteor-html-tools - v1.5.0
meteor-id-map - v1.3.0
meteor-minimongo - v1.3.1
meteor-mongo-id - v1.3.0 - Meteor Mongo ID package
meteor-observe-sequence - v1.5.1
meteor-ordered-dict - v1.3.0
meteor-random-window-crypto - v1.3.1
meteor-reactive-object-map - v1.4.6 - Reactive map helper for meteor blaze templates
meteor-reactive-var - v1.3.0
meteor-spacebars - v1.3.0
meteor-spacebars-compiler - v1.3.2
meteor-templating - v1.3.0
meteor-tinytest - v1.3.0
meteor-tracker - v1.3.0
spacebars-compiler - v1.6.0 - Spacebars compiler
```

**Comment by mitar** [comment] 2016-09-08 08:03
Thanks!

What I think would be the best is to have a NPM [scope](https://docs.npmjs.com/misc/scope) for Meteor/MDG/core packages and then we could use the same pacakge names for both Atmosphere and NPM packages.

**Comment by rwatts3** [comment] 2016-10-08 00:04
Is there any updates as to when blaze will be on npm ?

**Comment by mitar** [comment] 2016-10-08 00:07
We are waiting for MDG to move Tracker to NPM first. [See here](https://github.com/meteor/blaze/issues/13#issuecomment-248513072).

**Comment by filipenevola** [comment] 2021-03-18 19:31
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:31 UTC
Labels: MDG help needed
