### ISSUE TITLE
Template.parentData() in event handlers can't access the parent data context in the same template

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#193] opened 2016-12-03 02:56 UTC
Migrating this over from meteor/meteor#5491.

----

(originally reported by @lirbank)

Relates to meteor/meteor#3249
and possibly meteor/meteor#5280

Not sure if this is a bug but there is a confusing inconsistency between how parent (and current) data contexts can be accessed via {{../}} and via an event handler.

From an event handler Template.parentData() can only access the data context of a parent template (i.e. the element that fires the event have to be wrapped into a separate child template), not the parent data context in the same template.

But {{../}} can access the parent data context, regardless if it's in the same template or in a parent template.

I was for a while thinking that perhaps Meteor has both a concept of data contexts (defined by by `{{#with}}` or `{{#each}}`) and another concept of template data (defined by `<template>`), but it doesn't seem right. Looking at http://docs.meteor.com/#/full/template_parentdata it says Template.parentData() is used to "Accesses other data contexts that enclose the current data context." and "Template.parentData(2) is equivalent to {{../..}} in a template.", which would then not be true.

Clone this repo https://github.com/lirbank/meteor-data-context-test.git (vanilla Meteor 1.2.0.2)
Observe the browser console as you click the two buttons.
Please note that both buttons share the same event handler function.
Hope this is helpful, happy to provide more details if needed.

**Comment by micktaiwan** [comment] 2017-10-15 21:52
Can we expect a fix on this ?

**Comment by bitsofreedom** [comment] 2018-01-15 03:39
Workaround: use a `data` element get it with `$(event.target).data("name"):

```html
  <h2 class="ui header">{{question.text}}</h2>
  {{#each question.options}}
    <button class="ui button" data-relatedFact="{{question.relatedFact}}">
      {{text}}
    </button>
  {{/each}}
```

```js
<template name="question">
Template.question.events({
  'click button': function (event) {
    console.log($(event.target).data("relatedFact"));
  }
})
</template>
```

**Comment by micktaiwan** [comment] 2018-01-15 12:05
I think we all use workarounds at this point.

**Comment by mitar** [comment] 2018-01-15 20:15
Oh yes, this issue was one of main motivating ones for development of Blaze Components.

The issue is that currently we cannot really change much here without introducing backwards incompatibilities.

**Comment by filipenevola** [comment] 2021-03-18 19:37
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:37 UTC
