### ISSUE TITLE
Don't rerun helpers when an #each cursor limit changes

### ISSUE THREAD

**Issue by lorensr** [meteor/blaze#41] opened 2016-05-19 20:30 UTC
Migrated from https://github.com/meteor/meteor/issues/4960

When the argument to {{#each}} changes between different cursors, we treat the transition as if it is a change between two arrays. Since {{#each}} works with arbitrary arrays, we don't diff the items in the array. Instead, we inform all of the rendered items that their contents have changed (even though they likely haven't). This means many helpers will fire but their contents will stay the same.

The elegant solution in the framework would be to make minimongo smarter, giving it the intelligence to reuse materialized query results. You could imagine a minimongo that internally keeps ReactiveArrays of some sort that are updated incrementally and sliced and projected as needed for the purposes of queries.

**Comment by mitar** [comment] 2016-05-19 20:48
Can you expand description? Copy it over, make a summary?

**Comment by mitar** [comment] 2017-01-06 22:18
It would be great to have a reproduction here.

**Comment by filipenevola** [comment] 2021-03-18 19:32
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:32 UTC
