### ISSUE TITLE
Blaze, meteor's templates, are not usable with polymer's templates

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#187] opened 2016-11-29 13:50 UTC
Migrating this over from meteor/meteor#2765. @Slava's https://github.com/meteor/meteor/issues/2765#issuecomment-77049224 suggests a way forward on this.

----

(originally opened by @adaptabi)

Is there any example of how Polymer can be used in a meteor app?
I'm getting various errors e.g. : `Template has no 'name' attribute`

**Comment by mitar** [comment] 2016-11-29 20:40
I think this is maybe a duplicate of #71. In any case, I think path forward to this is to rename `.html` to `.blaze`, and then leave `.html` to be simply static HTML.

**Comment by mitar** [comment] 2016-11-29 20:41
Or, I think the issue is that people try to use Polymer at top-level. Maybe we should allow `<template>` to be nested inside top-level `<template>` with `<template>` inside not having any special effect.

**Comment by mitar** [comment] 2016-12-31 11:53
Closing this one in favor of #71. Let's have there all discussion about Polymer support and Blaze/Meteor.

**Closed by mitar** 2016-12-31 11:53 UTC
