### ISSUE TITLE
Array with undefined behaving weirdly. Bug?

### ISSUE THREAD

**Issue by juliomac** [meteor/blaze#264] opened 2017-07-18 01:42 UTC
This is possibly related to issue [203](https://github.com/meteor/blaze/issues/203).

I have my template:

      {{#each CurrentlyAllocated}}
	   <h4>Unit Allocated:<h1 class="label label-primary">{{this}}</h1></h4>
	  {{/each}}

then the helper:

       CurrentlyAllocated: function(){
         var allocated = MyCollection.findOne({_id:this._id},{fields:{Allocated:1}}).Allocated;
         var qty = MyCollection.findOne({_id:this._id}).Qty;

         var allocationtable = [];
     
            for (i=0; i < qty; i++){
                // if allocated has 2 itens and qty=4, it may create ["1", "2", undefined, undefined]
                allocationtable[i] = (allocated[i]);  
          }
        return allocationtable;

However, on screen it skips first index like this:

Unit Allocated:
Unit Allocated: 1
Unit Allocated: 2
Unit Allocated:

On console allocationtable = ["1", "2", undefined, undefined]

Why is it printing first one empty?

**Comment by mitar** [comment] 2017-07-18 01:53
Can you provide small reproduction? A repository with code for only this issue?

**Comment by filipenevola** [comment] 2021-03-18 19:41
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:41 UTC
