### ISSUE TITLE
Improve speed of removing templates

### ISSUE THREAD

**Issue by lorensr** [meteor/blaze#44] opened 2016-05-19 21:20 UTC
Migrated from https://github.com/meteor/meteor/issues/4352

Sometimes it takes a long enough time that it creates a bad user experience, eg a 340ms delay on one of my templates is a noticeable wait.

**Comment by mitar** [comment] 2016-05-19 21:51
I would like to see a reproduction for this with latest batch changes. To me it felt often that batching issues were attributed to Blaze, but they were in fact just batching issues.

**Comment by lorensr** [comment] 2016-05-19 22:29
The only recent batch changes I know of were to DDP – were there others?

**Comment by mitar** [comment] 2016-05-19 23:09
No, that is what I had in mind. I would like to see those issues with removal after those DDP changes code is in effect.

**Comment by lorensr** [comment] 2016-05-19 23:35
Why would DDP affect the removal of a template? It usually doesn't generate/require server communication. And in my case, I could tell from the profiling that the client wasn't receiving data pushed from the server at the time.

**Comment by mitar** [comment] 2016-05-20 00:14
Hm, maybe I am wrong, probably I am wrong. :-) But to me sometimes looked from profiling like that it was Blaze fault, but in fact was Minimongo. So maybe create a reproduction where you put static data into a data context, render that, and then remove it?

I am just saying that for me it is a bit unclear where is the issue at the moment. But I have not yet looked deeply into this. Just from my past experience.

**Comment by arggh** [comment] 2016-06-28 09:43
+1, I have a view (list with about 200 rows) that gets rendered quite fast: With template based subscription pattern the first rows fill the screen quickly. When I navigate away, it's a different story: my browser is in lockdown-mode for a good 5 seconds... Still trying to research the flamegraphs for the culprit, or is it just Blaze.. ?

**Comment by mitar** [comment] 2016-06-28 10:05
Which version of Meteor are you using?

**Comment by arggh** [comment] 2016-06-28 11:13
Meteor 1.3.4.1

**Comment by arggh** [comment] 2016-06-28 16:54
I can literally have the view render _blazin'_ fast (though some of the rows still keep updating below the fold after that for a few hundred ms), but navigating away locks my browser completely for a good few seconds. Really annoying that the rendering part, which is supposed to be the heavy one, is the easy one to handle.

This is the timeline screenshot of me trying to navigate away from a page with a table of 200 rows, each containing 3 sub-templates. I've selected the area where destroying the current template takes place.

<img width="1282" alt="chrome_timeline" src="https://cloud.githubusercontent.com/assets/17210302/16424745/1d4c4ed6-3d6a-11e6-8e51-c04e44c2ac04.png">

**Comment by arggh** [comment] 2016-06-28 17:05
I wonder if this has anything to do with the slowness of navigating away from a heavy template: [FlowRouter#292](https://github.com/kadirahq/flow-router/issues/292)

**Comment by mitar** [comment] 2016-06-28 17:07
Can somebody make a reproduction without flow router? Just rendering a big array of subtemplates, and then removing it to be replaced with another template? (if/else)? And see how long this takes?

**Comment by brown2rl** [comment] 2016-06-28 17:24
Mitar,

I may be able to do this later today with iron:router, is this still an issue?

Sent from my Windows Phone
________________________________

**Comment by mitar** [comment] 2016-06-28 17:27
No, no router. Just normal direct Blaze please. You are reporting this to Blaze repository, so please use only Blaze. Create a reproduction with Blaze.

**Comment by arggh** [comment] 2016-06-28 18:48
A quick and hasty reproduction can be found here: https://github.com/arggh/blaze-tmpl-destroy

I tried to simulate "real world" conditions by adding random data to each document which is then subscribed for. There isn't much reactivity in play though, I'll keep playing more with the repro later.

I got the 'hide list' -function to eat up 2.5 seconds of scripting time.

**Comment by mitar** [comment] 2016-06-28 18:50
Can you also try without a subscription? Just static array of random data?

**Comment by arggh** [comment] 2016-06-28 19:02
Sure, doesn't seem to make a difference: https://github.com/arggh/blaze-tmpl-destroy/tree/nosubs

**Comment by mitar** [comment] 2016-06-28 19:11
Thanks! This is great. Now we should just discover why is that. Without looking into Blaze I have two hypothesis:
* there are extra computations happening
* DOM is being removed one by one from leaf nodes up (it would be better if just the top is removed)

**Comment by arggh** [comment] 2016-06-28 19:54
I tested also with FlowRouter and ViewModel, neither of them had any significant effect on the issue. Looking at the flame graph, I'd put my money on the latter hypothesis...

<img width="838" alt="flame" src="https://cloud.githubusercontent.com/assets/17210302/16430233/485838ec-3d83-11e6-8439-8ee561d185f1.png">

**Comment by arggh** [comment] 2016-06-28 20:59
I've no clue how to fix this for real, but if you comment out the insides of this function in `blaze/dombackend.js` and replace it with `$jq.cleanData(elem)`, we get super snappy element removals and lots of memory leaks :)

```
tearDownElement: function (elem) {
   $jq.cleanData(elem);
/*
    var elems = [];
    // Array.prototype.slice.call doesn't work when given a NodeList in
    // IE8 ("JScript object expected").
    var nodeList = elem.getElementsByTagName('*');
    for (var i = 0; i < nodeList.length; i++) {
      elems.push(nodeList[i]);
    }
    elems.push(elem);
    $jq.cleanData(elems);
*/
  }
```

**Comment by arggh** [comment] 2016-06-29 10:36
@mitar Should all Blaze related issues reside here in this repo? In the Meteor contribution guide there's no mention of it.

**Comment by mitar** [comment] 2016-06-29 13:51
We have not yet made full transition, but this is a plan long-term, yes. So yes, open new ones here as well.

**Comment by aadamsx** [comment] 2016-06-29 17:36
@arggh what flame graph software are you using?

**Comment by arggh** [comment] 2016-06-29 17:38
Just Google Chrome's (Canary) dev tools.

**Comment by aadamsx** [comment] 2016-06-29 17:49
@arggh, thanks, I got the "timeline" tab, but what of the flame graph, which tab is that?

**Comment by lorensr** [comment] 2016-06-29 20:04
When you record on the Timeline tab while Capture: JS Profile is checked,
you'll get a flamechart at the end.

**Comment by arggh** [comment] 2016-07-13 06:39
This issue will be fixed, or at least very much improved, in Meteor `1.4` with a change in Tracker (https://github.com/meteor/meteor/pull/7328)

**Comment by arggh** [comment] 2016-08-10 16:34
@lorensr Have you tried revisiting your benchmarks with the updated Tracker?

**Comment by mitar** [comment] 2016-09-30 05:14
One [observation from my benchmarking tool](https://github.com/mitar/meteor-blaze-benchmark) is that a lot of time is spent on cleaning up jQuery event handlers. I think that #109 should improve this a lot because they do not use jQuery to hook-up event handlers.

**Comment by mitar** [comment] 2016-09-30 05:14
@arggh: Can you check my benchmark and see if you observe the same things you see in your code?

**Comment by arggh** [comment] 2016-10-01 08:44
@mitar I do. Checking my own test case using Meteor 1.4.2-beta.5, most of the time is spent on jQuery's `cleanData`.

As a sidenote, removing templates is no longer the bottle neck in my use case, it's quite snappy after the Tracker fix applied in meteor/meteor#7328 . Not saying there ain't room for some improvement.

Now the bottleneck (in my test case) is clearly constructing the templates, but the flamegraphs seem to point at Minimongo.

**Comment by mitar** [comment] 2016-10-01 09:14
Yea, observes take a lot of time.

If you find any ways to improve things further, I am all ears. :-)

**Comment by mitar** [comment] 2016-10-01 09:14
Also, I want to create reproducible and realistic benchmarks, so that we can work together on improving them. If you have ideas how to improve current benchmarks, or add more cases, please contribute as well. :-)

**Comment by filipenevola** [comment] 2021-03-18 19:31
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Closed by filipenevola** 2021-03-18 19:31 UTC
Labels: contributions welcome

**Comment by arggh** [comment] 2021-03-18 19:34
@filipenevola I think it was ripe for closing, fixed in https://github.com/meteor/meteor/pull/7328 5 years ago...

**Comment by filipenevola** [comment] 2021-03-18 23:16
@arggh thank you for your contribution 😉

**Comment by aadamsx** [comment] 2021-03-18 23:54
That's a great point @arggh, @filipenevola are you reviving Blaze?  This project has been left dorman for years.

**Comment by filipenevola** [comment] 2021-03-19 00:05
> That's a great point @arggh, @filipenevola are you reviving Blaze?  This project has been left dorman for years.

Blaze is active. 

Blaze HMR is almost done for example https://forums.meteor.com/t/blaze-hmr-beta-2-is-available/55473
